/**
 * 브리핑 시계열 적재 가드 (2026-08-17 세션N-38).
 *
 * 🔴 **왜**: `briefing-runner.ts` 는 `persistAuditTracking` 을 **부르지 않았다.**
 *   호출처가 `runner.ts` 한 곳뿐이라 브리핑 결과는 `AuditJob.result` JSON 에만 남고
 *   **`Tracking` 에는 한 줄도 안 쌓였다.**
 *   [실측 2026-08-17] `Tracking` 엔진별 집계에 `naver-briefing` 행 **0개**
 *   (브리핑이 11번 돌았는데도). = N-36 과 같은 유형의 조용한 유실.
 *
 * 🔴🔴 **그리고 고치는 과정에서 2차 사고를 발견했다**: `tracking.ts` 가
 *   `isAutoGenerated: true` 를 **하드코딩**하고 있었다. 브리핑 질의를 그대로 심었으면
 *   무료 고객(상한 5개)이 측정 한 번에 할당량을 잃고 마법사가
 *   「상한 도달, 요금제를 올리세요」라고 **거짓 안내**했을 것이다.
 *   → 축 파라미터(`promptIsAutoGenerated`)를 뚫고 브리핑은 **false** 를 넘긴다.
 *
 * ⚠️ 이 테스트는 **소스를 읽어 계약을 검사**한다(`fallback-prompt-persist.test.ts` 와 같은 방식).
 *   DB 없이 도는 가드라 CI 에서 회귀를 즉시 잡는다.
 *
 * @vitest-environment node
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "vitest";

const ROOT = join(import.meta.dirname, "../../..");
const BRIEFING = join(ROOT, "packages/audit/briefing-runner.ts");
const TRACKING = join(ROOT, "packages/audit/tracking.ts");
const SUGGEST = join(ROOT, "apps/app/app/actions/brand/suggest-prompts.ts");

/**
 * 주석을 걷고 **실행 코드만** 남긴다.
 * 🔴 줄머리뿐 아니라 **줄 끝 주석**도 자른다 — 그러지 않으면
 *   `isAutoGenerated: true, // false` 한 줄이 검사를 통과한다(N-36 에서 실제로 뚫렸다).
 *   문자열 리터럴 안의 `//`(URL 등)는 따옴표 상태를 보고 보존한다.
 */
const stripToCode = (raw: string): string => {
  const out: string[] = [];
  let inBlock = false;
  for (const line of raw.split("\n")) {
    const t = line.trim();
    if (inBlock) {
      if (t.includes("*/")) {
        inBlock = false;
      }
      continue;
    }
    if (t.startsWith("//") || t.startsWith("*")) {
      continue;
    }
    if (t.startsWith("/*")) {
      if (!t.includes("*/")) {
        inBlock = true;
      }
      continue;
    }
    let quote: string | null = null;
    let cut = -1;
    for (let i = 0; i < line.length; i++) {
      const c = line[i] as string;
      if (quote) {
        if (c === "\\") {
          i++;
        } else if (c === quote) {
          quote = null;
        }
        continue;
      }
      if (c === '"' || c === "'" || c === "`") {
        quote = c;
        continue;
      }
      if (c === "/" && line[i + 1] === "/") {
        cut = i;
        break;
      }
    }
    out.push(cut >= 0 ? line.slice(0, cut) : line);
  }
  return out.join("\n");
};

const briefingCode = stripToCode(readFileSync(BRIEFING, "utf8"));
const trackingCode = stripToCode(readFileSync(TRACKING, "utf8"));
const suggestCode = stripToCode(readFileSync(SUGGEST, "utf8"));

// ── 검사 패턴(상수) — 인라인 정규식은 lint/performance/useTopLevelRegex 위반 ──
const IMPORTS_PERSIST = /import \{[^}]*persistAuditTracking/;
const CALLS_PERSIST = /await persistAuditTracking\(\{/;
const SELECTS_ORG = /organizationId:\s*true/;
const SELECTS_BRAND = /brandId:\s*true/;
const PASSES_ORG = /organizationId:\s*jobBefore\.organizationId/;
const PASSES_BRAND = /brandId:\s*jobBefore\.brandId/;
const USES_ADOPTED_PROMPT = /promptText:\s*adoptedPrompt/;
const SKIP_LOG = /audit\.briefing\.tracking_skipped/;
const SKIP_REASON = /reason:/;
const BRIEFING_FLAG_FALSE = /promptIsAutoGenerated:\s*false/;
const TRACKING_HARDCODES_TRUE =
  /create:\s*\{[\s\S]{0,200}?isAutoGenerated:\s*true/;
const TRACKING_USES_PARAM =
  /create:\s*\{[\s\S]{0,200}?isAutoGenerated:\s*promptIsAutoGenerated/;
const DEFAULT_IS_TRUE = /promptIsAutoGenerated\s*=\s*true/;
const LIMIT_COUNTS_TRUE =
  /prompt\.count\(\{[\s\S]{0,80}isAutoGenerated:\s*true/;

describe("브리핑 시계열 적재 — Tracking 이 비지 않는다", () => {
  test("🔴 브리핑 러너가 persistAuditTracking 을 실제로 호출한다", () => {
    // 이게 없으면 브리핑은 영원히 스냅샷이고 추세·비교에 안 잡힌다.
    expect(briefingCode).toMatch(IMPORTS_PERSIST);
    expect(briefingCode).toMatch(CALLS_PERSIST);
  });

  test("org·brand 를 job 에서 읽어 넘긴다 — 없으면 적재가 불가능하다", () => {
    expect(briefingCode).toMatch(SELECTS_ORG);
    expect(briefingCode).toMatch(SELECTS_BRAND);
    expect(briefingCode).toMatch(PASSES_ORG);
    expect(briefingCode).toMatch(PASSES_BRAND);
  });

  test("🔴 브리핑이 실제로 던진 질의를 promptText 로 넘긴다", () => {
    // 본류 프롬프트(추천형)가 아니라 브리핑 자체 질의(정보형)여야 축이 맞는다.
    expect(briefingCode).toMatch(USES_ADOPTED_PROMPT);
  });

  test("🔴 건너뛸 때 이유를 남긴다 — 조용한 실패 금지(N-36 교훈)", () => {
    expect(briefingCode).toMatch(SKIP_LOG);
    expect(briefingCode).toMatch(SKIP_REASON);
  });
});

describe("🔴 요금제 할당량 축 — 브리핑이 고객 상한을 먹지 않는다", () => {
  test("브리핑은 promptIsAutoGenerated: false 를 명시해 넘긴다", () => {
    // 🔴 이 줄이 사라지면 tracking.ts 기본값(true)이 적용돼
    //   무료 고객 상한 5개를 브리핑 질의가 잠식한다.
    expect(briefingCode).toMatch(BRIEFING_FLAG_FALSE);
  });

  test("🔴 tracking.ts 가 축을 하드코딩하지 않는다", () => {
    // create 블록 안이 리터럴 true 면 호출부가 무엇을 넘기든 무시된다.
    expect(trackingCode).not.toMatch(TRACKING_HARDCODES_TRUE);
    expect(trackingCode).toMatch(TRACKING_USES_PARAM);
  });

  test("기본값은 true — 기존 호출부(runner.ts) 동작이 안 바뀐다", () => {
    expect(trackingCode).toMatch(DEFAULT_IS_TRUE);
  });

  test("마법사 상한 계산은 여전히 true 만 센다", () => {
    // 이 조건이 바뀌면 시스템 질의가 상한에 섞여 축 분리가 무너진다.
    expect(suggestCode).toMatch(LIMIT_COUNTS_TRUE);
  });
});
