/*
 * 🔴 **폴백 프롬프트를 DB에 심는다 — 안 심으면 시계열이 통째로 증발한다** (2026-08-16).
 *
 * ## 막는 사고 (실측으로 확인된 것)
 * `[실측 2026-08-16]` 브랜드 8개 전수 대조 — **Prompt 0 인 브랜드는 Tracking 도 정확히 0**:
 *   메디큐브 0/0 · 아누아 0/0 · 토니모리 0/0 · 이니스프리 0/0 · 애플 0/0
 *   (반대로 마법사로 프롬프트를 저장한 나이키 5/34 · 엔비디아 5/20 · 설화수 4/21 은 살아남았다)
 *   → org 측정 **34회 중 24회분의 시계열이 통째로 유실**됐다.
 *
 * 원인: 폴백 프롬프트는 **메모리에만** 존재했다. `persistAuditTracking` 이
 *   `prompt.upsert(brandId_text)` 로 이을 **promptId 를 만들 수 없어** 적재가 조용히 끝난다.
 *   ⚠️ 그 함수는 best-effort 라 **throw 하지 않는다** → 측정은 `completed`, 화면도 정상,
 *   **시계열만 사라진다.** 3주간 아무에게도 안 보였고, 인계서 7개가 이걸
 *   *"P0 실고객이 없어서"* 라고 잘못 적었다.
 *
 * ## 🔴 같이 막는 두 번째 사고 — 요금제 할당량 잠식
 * `isAutoGenerated` 는 이미 「프롬프트 마법사」의 **요금제 상한 계산**에 쓰인다
 *   (`suggest-prompts.ts` — free 5 / starter 30 / growth 150).
 *   폴백을 `true` 로 심으면 **무료 고객이 측정 한 번에 할당량 4개를 모르는 사이 잃고**,
 *   마법사가 *"상한에 도달했어요. 요금제를 올려주세요"* 라고 **거짓 안내**한다.
 *   → 축을 분리한다: **true = 고객이 고른 추적 대상 / false = 시스템 기본 질문.**
 *
 * ⚠️ 문구가 아니라 **계약**을 검사한다:
 *   ① 폴백을 **심고 나서** 반환한다 ② `isAutoGenerated: false` 로 심는다
 *   ③ upsert 로 심는다(재실행 시 promptId 안정 = 시계열 선 분열 방지)
 *   ④ 심기 실패가 **측정을 죽이지 않는다** ⑤ 조회 조건은 **true 그대로**(마법사 무변경)
 *
 * @vitest-environment node
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, test } from "vitest";

const RUNNER = join(import.meta.dirname, "../../../packages/audit/runner.ts");
const SUGGEST_PROMPTS = join(
  import.meta.dirname,
  "../app/actions/brand/suggest-prompts.ts"
);

/*
 * 주석·import 를 걷어낸 실제 코드 — **주석 문구가 검사를 통과시키지 않도록**.
 * 🔴 정규식으로 블록주석을 지우지 않는다(N-26 에 40,570자를 삼킨 사고).
 *   → 줄 단위 상태 기계를 쓴다.
 */
const stripToCode = (raw: string): string => {
  const out: string[] = [];
  let inBlock = false;
  for (const line of raw.split("\n")) {
    const t = line.trimStart();
    if (inBlock) {
      if (t.includes("*/")) {
        inBlock = false;
      }
      continue;
    }
    if (t.startsWith("//") || t.startsWith("import")) {
      continue;
    }
    if (t.startsWith("/*") || t.startsWith("{/*")) {
      if (!t.includes("*/")) {
        inBlock = true;
      }
      continue;
    }
    /*
     * 🔴 **줄 끝 주석도 잘라낸다.** 줄머리 주석만 걷으면
     *   `isAutoGenerated: true, // isAutoGenerated: false` 한 줄이 검사를 통과한다
     *   (뮤테이션 4에서 실제로 뚫렸다). 문자열 리터럴 안의 `//`(URL 등)는
     *   따옴표 상태를 보고 건너뛴다.
     */
    let quote: string | null = null;
    let cut = -1;
    for (let i = 0; i < line.length; i++) {
      const c = line[i] as string;
      if (quote) {
        if (c === "\\") {
          i++;
        } else if (c === quote) {
          quote = null;
        }
        continue;
      }
      if (c === '"' || c === "'" || c === "`") {
        quote = c;
        continue;
      }
      if (c === "/" && line[i + 1] === "/") {
        cut = i;
        break;
      }
    }
    out.push(cut >= 0 ? line.slice(0, cut) : line);
  }
  return out.join("\n");
};

const runnerCode = stripToCode(readFileSync(RUNNER, "utf8"));
const suggestCode = stripToCode(readFileSync(SUGGEST_PROMPTS, "utf8"));

/** 폴백을 **심는 함수가 존재**한다. */
const HAS_PERSIST_FN = /async function persistFallbackPrompts\(/;
/** 빈 결과일 때 **심고 나서** 반환한다(그냥 generate 만 반환하면 유실 재발). */
const AWAITS_PERSIST_ON_EMPTY =
  /saved\.length === 0[\s\S]{0,120}return await persistFallbackPrompts\(/;
/** 🔴 upsert 로 심는다 — create 만 쓰면 재실행 시 유니크 충돌 or promptId 분열. */
const USES_UPSERT = /tx\.prompt\.upsert\(/;
/** upsert 키가 `brandId_text` — 시계열 안정의 근거. */
const UPSERT_KEY = /where:\s*\{\s*brandId_text:\s*\{\s*brandId,\s*text:/;

/**
 * 🔴🔴 **핵심 가드**: 폴백은 `isAutoGenerated: false` 로 심어야 한다.
 *   true 로 바뀌면 무료 고객 할당량 5개 중 4개가 조용히 사라진다.
 *
 * ⚠️ **`create:` 블록 안**을 본다. 그냥 `/isAutoGenerated:\s*false/` 로 두면
 *   주석 한 줄이 검사를 만족시켜 **장식 가드**가 된다(뮤테이션에서 실제로 확인했다 —
 *   이 저장소가 가드에 4번 뚫린 것과 같은 형태). stripToCode 가 줄머리 주석은
 *   걷어내지만 **줄 끝 주석·JSDoc 안 문구**는 남으므로 위치까지 못박는다.
 */
const PERSIST_FLAG_FALSE =
  /create:\s*\{[\s\S]{0,200}?isAutoGenerated:\s*false[\s\S]{0,40}?\}/;

/** 심기 실패가 측정을 죽이지 않는다(try/catch 로 감싸고 폴백을 그대로 반환). */
const PERSIST_IS_BEST_EFFORT =
  /catch \(error\)[\s\S]{0,200}fallback_persist_failed/;

/** 조회 조건은 **true 그대로** — 마법사가 고른 것만 추적 대상으로 읽는다. */
const QUERY_STILL_TRUE =
  /findMany\(\{[\s\S]{0,80}where:\s*\{\s*brandId,\s*isAutoGenerated:\s*true/;

/** 마법사의 상한 계산이 **여전히 true 만 센다**(폴백이 안 섞인다). */
const LIMIT_COUNTS_ONLY_TRUE =
  /prompt\.count\(\{[\s\S]{0,80}isAutoGenerated:\s*true/;

describe("폴백 프롬프트 적재 — 시계열 유실 방지", () => {
  test("폴백을 심는 함수가 있고, 빈 결과일 때 심고 나서 반환한다", () => {
    expect(runnerCode).toMatch(HAS_PERSIST_FN);
    expect(runnerCode).toMatch(AWAITS_PERSIST_ON_EMPTY);
  });

  test("upsert(brandId_text) 로 심는다 — 재실행해도 promptId 가 안 갈린다", () => {
    expect(runnerCode).toMatch(USES_UPSERT);
    expect(runnerCode).toMatch(UPSERT_KEY);
  });

  test("🔴 폴백은 isAutoGenerated:false — 고객 요금제 할당량을 먹지 않는다", () => {
    expect(runnerCode).toMatch(PERSIST_FLAG_FALSE);
  });

  test("심기 실패가 측정을 죽이지 않는다(best-effort)", () => {
    expect(runnerCode).toMatch(PERSIST_IS_BEST_EFFORT);
  });

  test("조회·상한 계산은 true 그대로 — 마법사 동작 무변경", () => {
    expect(runnerCode).toMatch(QUERY_STILL_TRUE);
    expect(suggestCode).toMatch(LIMIT_COUNTS_ONLY_TRUE);
  });
});
