import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = process.cwd();
const read = (path: string) => readFileSync(join(root, path), "utf8");

describe("question result drilldown", () => {
  it("links measured dashboard questions to their original answers", () => {
    expect(read("app/(authenticated)/components/prompt-scoreboard.tsx")).toContain(
      '`/prompts/${score.promptId}`'
    );
    expect(read("app/(authenticated)/lib/dashboard-data.ts")).toContain(
      "promptId: group[0]?.promptId"
    );
  });

  it("shows default and user-selected questions in the prompts tab", () => {
    const source = read("app/(authenticated)/prompts/page.tsx");
    expect(source).toContain("isAutoGenerated: false");
    expect(source).toContain("기본 측정 질문");
  });

  it("scopes raw answers by organization and limits the queried history", () => {
    const source = read("app/(authenticated)/prompts/[promptId]/page.tsx");
    expect(source).toContain("brand: { organizationId: orgId }");
    expect(source).toContain("rawResponse: true");
    expect(source).toContain("take: 70");
  });
});
