/**
 * 🔴 **왜 이 가드가 있나** (세션N-41 — 「추적 질문」 탭)
 *
 * 경쟁사 4곳이 전부 `Prompts` 를 최상위 탭으로 갖는데 우리는 `PromptWizard` 를
 * `/brand` 안에 묻어 뒀다. 이 탭이 그걸 꺼냈고, **목록과 삭제**를 새로 줬다.
 *
 * 이 화면은 **지우는 화면**이라 조용히 깨지면 피해가 되돌릴 수 없다:
 *   ① org 스코프가 빠지면 **남의 조직 질문을 지울 수 있다**
 *   ② `isAutoGenerated` 축이 섞이면 **시스템 기본질문이 지워져 폴백 측정이 깨진다**
 *   ③ Cascade 고지가 빠지면 **과거 시계열이 조용히 사라진다**
 *   ④ 사이드바 링크가 빠지면 탭이 **도달 불가**가 된다(=이 작업의 존재 이유가 사라짐)
 *
 * ⚠️ 네트워크·DB 를 타지 않는다 — 소스의 **계약**만 검사한다.
 *   📕 규율: 가드는 문구가 아니라 계약을 검사한다(reference_findable_traps §1).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const read = (relative: string): string =>
  readFileSync(join(process.cwd(), relative), "utf8");

/**
 * 주석을 걷고 **실행되는 코드만** 남긴다.
 * 🔴 이 저장소는 가드가 **자기 주석을 세어** 오판한 사고를 여러 번 겪었다
 *   (N-36 줄끝 주석 · N-39 JSX 주석 · N-41 뮤테이션 오판).
 *   ⚠️ 문자열 리터럴 안의 `//` 는 보존한다.
 */
function stripToCode(source: string): string {
  // 🔴 `\{\s*\/\*` (여는 중괄호와 `/*` 사이 공백 허용)는 **과잉 삭제**한다 —
  //   템플릿 리터럴의 `${...}` 같은 중괄호에서 시작해 뒤쪽 `*/` 까지 통째로 삼켰다.
  //   실측(N-41): `deletedTrackings` 2건이 **0건으로** 사라져 멀쩡한 코드를
  //   "계약 위반"으로 오판했다(가드가 자기 실수로 코드를 지운 것).
  //   → `{/*` 가 **붙어 있을 때만** JSX 주석으로 본다.
  const withoutJsx = source.replaceAll(/\{\/\*[\s\S]*?\*\/\}/g, "");
  return withoutJsx
    .split("\n")
    .map((line) => {
      let inSingle = false;
      let inDouble = false;
      let inTick = false;
      for (let i = 0; i < line.length; i++) {
        const c = line[i];
        if (line[i - 1] === "\\") {
          continue;
        }
        if (c === "'" && !(inDouble || inTick)) {
          inSingle = !inSingle;
        } else if (c === '"' && !(inSingle || inTick)) {
          inDouble = !inDouble;
        } else if (c === "`" && !(inSingle || inDouble)) {
          inTick = !inTick;
        } else if (
          c === "/" &&
          line[i + 1] === "/" &&
          !(inSingle || inDouble || inTick)
        ) {
          return line.slice(0, i);
        }
      }
      return line;
    })
    .filter((line) => !line.trimStart().startsWith("*"))
    .join("\n");
}

const deleteAction = stripToCode(read("app/actions/brand/delete-prompt.ts"));
const page = stripToCode(read("app/(authenticated)/prompts/page.tsx"));
const list = stripToCode(read("app/(authenticated)/prompts/prompt-list.tsx"));
const sidebar = stripToCode(read("app/(authenticated)/components/sidebar.tsx"));

// 정규식은 최상위에(lint: useTopLevelRegex).
/** ① org 스코프 — 세션에서 재도출 + 브랜드 소유 검증. */
const REQUIRE_ORG = /requireOrg\(\)/;
const SCOPED_BRAND = /scopedBrandById\(/;
/** ② 축 분리 — 고객이 고른 것만 지운다. */
const REJECTS_SYSTEM_PROMPT = /!\s*prompt\.isAutoGenerated/;
/** 목록도 같은 축만 읽는다. */
const LIST_FILTERS_AXIS = /isAutoGenerated:\s*true/;
/** ③ Cascade 고지 — 사라지는 행 수를 세서 반환한다. */
const COUNTS_TRACKINGS = /tracking\.count\(/;
const RETURNS_DELETED_COUNT = /deletedTrackings/;
/** ④ 사이드바 도달 경로. */
const SIDEBAR_LINK = /url:\s*"\/prompts"/;
/** 상한을 화면이 다시 정의하지 않는다(단일 진실 = planCapabilities). */
const LIMIT_FROM_PLAN = /planCapabilities\(\w+\)\.promptLimit/;
/** 상한 숫자를 화면에 박았는가(free5/starter30/growth150 복제 금지). */
const HARDCODED_LIMIT = /promptLimit\s*=\s*\d+|\b(?:30|150|500)\s*개 중/;
/**
 * 서버액션을 **값으로** import 했는가(= 번들에 `node:*` 가 끌려온다).
 * `import type { ... }` 은 컴파일 시 지워지므로 위반이 아니다 → `type` 이 없는 것만 잡는다.
 */
const VALUE_IMPORTS_ACTION =
  /import\s+\{[^}]*\bdeletePromptAction\b[^}]*\}\s+from/;
/** 주입 계약. */
const INJECTS_ON_DELETE = /onDelete\?:|onDelete\s*\}/;
/** 주입이 없을 때 버튼을 감추는가. */
const GUARDS_BUTTON_ON_INJECTION = /\{onDelete\s*\?/;

describe("추적 질문 탭 — 삭제의 안전 계약", () => {
  it("🔒 org 를 세션에서 재도출한다", () => {
    expect(
      deleteAction,
      "requireOrg 가 없다 — 비로그인/조직 미선택 상태로 삭제가 들어온다"
    ).toMatch(REQUIRE_ORG);
  });

  it("🔒 질문의 소유 브랜드가 현재 org 소속인지 검증한다", () => {
    expect(
      deleteAction,
      "scopedBrandById 가 없다 — **남의 조직 질문을 지울 수 있다**"
    ).toMatch(SCOPED_BRAND);
  });

  it("🔴 시스템 기본질문(isAutoGenerated:false)은 지우지 않는다", () => {
    // 지우면 폴백 측정이 이을 원장이 사라진다(N-36 사고의 반대편).
    expect(
      deleteAction,
      "축 검사가 없다 — 시스템 기본질문이 지워져 폴백 측정이 깨진다"
    ).toMatch(REJECTS_SYSTEM_PROMPT);
  });

  it("🔴 사라지는 측정 기록 수를 세서 반환한다(Cascade 고지)", () => {
    // Tracking.promptId 는 onDelete: Cascade — 조용히 지우면 시계열이 유실된다.
    expect(deleteAction, "삭제될 Tracking 수를 세지 않는다").toMatch(
      COUNTS_TRACKINGS
    );
    expect(deleteAction, "사라진 건수를 화면에 알리지 않는다").toMatch(
      RETURNS_DELETED_COUNT
    );
  });

  it("🔴 화면이 사라지는 건수를 사용자에게 밝힌다", () => {
    expect(
      list,
      "화면이 deletedTrackings 를 쓰지 않는다 — 무엇이 사라졌는지 말하지 않는다"
    ).toMatch(RETURNS_DELETED_COUNT);
  });

  it("🔴 목록이 서버액션을 import 하지 않는다(주입만 받는다)", () => {
    // 실측(N-41): 직접 import 하면 `node:fs`·`node:crypto` 가 브라우저 번들로 끌려와
    //   **Storybook preview 빌드가 전체 실패**한다(내 스토리만이 아니라 21장 전부).
    //   📕 N-37 과 같은 함정 → 주입 패턴이 규칙이다.
    //   ⚠️ `import type` 은 컴파일 시 지워지므로 안전 = 값 import 만 잡는다.
    expect(
      list,
      "서버액션을 값으로 import 했다 — Storybook 빌드가 통째로 깨진다"
    ).not.toMatch(VALUE_IMPORTS_ACTION);
    expect(list, "onDelete 주입을 받지 않는다").toMatch(INJECTS_ON_DELETE);
  });

  it("주입이 없으면 삭제 버튼을 렌더하지 않는다(가짜 컨트롤 금지)", () => {
    expect(
      list,
      "onDelete 없이도 버튼을 그린다 — 눌러도 아무 일 없는 버튼이 생긴다"
    ).toMatch(GUARDS_BUTTON_ON_INJECTION);
  });
});

describe("추적 질문 탭 — 도달 경로와 단일 진실", () => {
  it("🔴 사이드바에 링크가 있다(없으면 탭이 도달 불가)", () => {
    expect(
      sidebar,
      "사이드바 링크가 없다 — 이 탭을 만든 이유(묻혀 있던 자산을 꺼내기)가 사라진다"
    ).toMatch(SIDEBAR_LINK);
  });

  it("목록도 고객이 고른 질문만 읽는다", () => {
    expect(page, "isAutoGenerated 필터가 없다").toMatch(LIST_FILTERS_AXIS);
  });

  it("🔴 상한은 planCapabilities 하나에서 온다", () => {
    expect(
      page,
      "상한을 플랜 사전에서 읽지 않는다 — 저장 로직과 화면이 갈린다"
    ).toMatch(LIMIT_FROM_PLAN);
  });

  it("🔴 상한 숫자를 화면에 하드코딩하지 않는다", () => {
    expect(
      page,
      "상한이 상수로 박혔다 — 요금제가 바뀌면 화면만 거짓이 된다"
    ).not.toMatch(HARDCODED_LIMIT);
  });
});
