/** @vitest-environment node */

import { execFileSync, spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { toBriefingTaggedResponses } from "@repo/audit/briefing-tracking";
import {
  claimAuditTracking,
  finalizeAuditTracking,
  reconcileAuditTracking,
} from "@repo/audit/reconcile-audit-tracking";
import {
  claimBriefingTracking,
  finalizeBriefingTracking,
  reconcileBriefingTracking,
} from "@repo/audit/reconcile-briefing-tracking";
import { sweepAuditTrackingReconciliation } from "@repo/audit/sweep-audit-tracking";
import { tagCoreResponses } from "@repo/audit/tracking";
import { retireExhaustedTrackingClaim } from "@repo/audit/tracking-replay-policy";
import { PrismaClient } from "@repo/database/generated/client";
import { PrismaPg } from "@repo/database/node_modules/@prisma/adapter-pg/dist/index.mjs";
import { afterAll, describe, expect, it, vi } from "vitest";

const state = vi.hoisted(() => ({ database: null as unknown }));
vi.mock("@repo/database", () => ({
  get database() {
    return state.database;
  },
}));
vi.mock("@repo/observability/log", () => ({
  log: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));
vi.mock("@repo/ai/lib/engines", () => ({
  costOf: () => ({ krw: 0, basis: "test" }),
}));

const { persistAuditTracking } = await import("@repo/audit/tracking");
const { commitBriefingResult } = await import("@repo/audit/briefing-runner");
const tempDir = mkdtempSync("/tmp/findable-tracking-prisma-");
const socketDir = join(tempDir, "socket");
const port = 15_732 + Math.floor(Math.random() * 100);
const role = execFileSync("id", ["-un"], { encoding: "utf8" }).trim();
const connectionString = `postgresql://${role}@127.0.0.1:${port}/postgres?application_name=findable_tracking_prisma`;
let serverStarted = false;
// initdb/postmaster abort on macOS without a valid locale
// ("postmaster became multithreaded during startup"), so pin C locale here.
const pgEnv = { ...process.env, LC_ALL: "C", LANG: "C" };

function run(command: string, args: string[]) {
  const result = spawnSync(command, args, { encoding: "utf8", env: pgEnv });
  if (result.status !== 0) {
    throw new Error(`${command} failed: ${result.stderr || result.stdout}`);
  }
}

function startDatabase() {
  run("initdb", ["-D", tempDir, "-A", "trust", "--no-locale"]);
  mkdirSync(socketDir);
  run("pg_ctl", [
    "-D",
    tempDir,
    "-o",
    `-p ${port} -k ${socketDir}`,
    "-l",
    join(tempDir, "postgres.log"),
    "start",
  ]);
  serverStarted = true;
  const deadline = Date.now() + 5000;
  while (Date.now() < deadline) {
    if (
      spawnSync("pg_isready", ["-h", "127.0.0.1", "-p", String(port)])
        .status === 0
    ) {
      return;
    }
  }
  throw new Error("PostgreSQL readiness timed out");
}

afterAll(() => {
  if (serverStarted) {
    spawnSync(
      "pg_ctl",
      [
        "-D",
        tempDir,
        "-o",
        `-p ${port} -k ${socketDir}`,
        "stop",
        "-m",
        "immediate",
      ],
      { stdio: "ignore" }
    );
  }
  rmSync(tempDir, { recursive: true, force: true });
});

describe("product Tracking replay through PrismaPg", () => {
  it("GREEN characterization: replay and contention converge to one row per run key", async () => {
    startDatabase();
    const database = new PrismaClient({
      adapter: new PrismaPg({ connectionString, max: 1 }),
    });
    state.database = database;
    try {
      await database.$executeRawUnsafe(`
        CREATE TYPE "PromptLanguage" AS ENUM ('ko', 'en');
        CREATE TYPE "PromptCategory" AS ENUM ('custom');
        CREATE TYPE "EngineProvider" AS ENUM ('naver');
        CREATE TYPE "EngineLanguage" AS ENUM ('ko');
        CREATE TYPE "Sentiment" AS ENUM ('positive', 'neutral', 'negative');
        CREATE TABLE "Organization" ("id" text PRIMARY KEY);
        CREATE TABLE "Brand" ("id" text PRIMARY KEY, "organizationId" text NOT NULL);
        CREATE TABLE "Engine" ("id" text PRIMARY KEY, "name" text NOT NULL, "provider" "EngineProvider" NOT NULL, "language" "EngineLanguage" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "ordering" integer NOT NULL DEFAULT 0);
        CREATE TABLE "Prompt" ("id" text PRIMARY KEY, "brandId" text NOT NULL, "text" text NOT NULL, "language" "PromptLanguage" NOT NULL, "category" "PromptCategory", "isAutoGenerated" boolean NOT NULL DEFAULT false, "createdAt" timestamptz NOT NULL DEFAULT now(), UNIQUE ("brandId", "text"));
        CREATE TABLE "Tracking" ("id" text PRIMARY KEY, "brandId" text NOT NULL, "promptId" text NOT NULL, "engineId" text NOT NULL, "rawResponse" text, "brandMentioned" boolean NOT NULL DEFAULT false, "mentionPosition" integer, "mentionListSize" integer, "sentiment" "Sentiment", "citedSources" jsonb NOT NULL DEFAULT '[]', "shareOfVoice" double precision, "errorMessage" text, "trackedAt" timestamptz NOT NULL DEFAULT now(), "inputTokens" integer, "outputTokens" integer, "costKrw" double precision, "costBasis" text);
        CREATE TABLE "AuditJob" ("id" text PRIMARY KEY, "status" text NOT NULL, "organizationId" text, "brandId" text, "completedAt" timestamptz, "result" jsonb, "postprocessing" jsonb);
        CREATE TABLE "ReconcileWriterEntry" ("worker" text PRIMARY KEY);
        INSERT INTO "Organization" ("id") VALUES ('org-replay');
        INSERT INTO "Brand" ("id", "organizationId") VALUES ('brand-replay', 'org-replay');
        INSERT INTO "Engine" ("id", "name", "provider", "language") VALUES ('naver-briefing', 'Naver Briefing', 'naver', 'ko');
      `);
      const migrationPath = fileURLToPath(
        new URL(
          "../../../packages/database/prisma/migrations/20261004_tracking_row_key/migration.sql",
          import.meta.url
        )
      );
      await database.$executeRawUnsafe(readFileSync(migrationPath, "utf8"));
      const workerB = new PrismaClient({
        adapter: new PrismaPg({ connectionString, max: 1 }),
      });
      try {
        const concurrentStartedAt = new Date("2026-10-04T01:00:00.000Z");
        await database.$executeRawUnsafe(
          `INSERT INTO "AuditJob" ("id", "status", "postprocessing") VALUES ('job-concurrent-claim', 'completed', '{"tracking":"unknown"}'::jsonb), ('job-stale-claim', 'completed', '{"tracking":"unknown"}'::jsonb)`
        );
        const [claimA, claimB] = await Promise.all([
          claimAuditTracking(
            database,
            "job-concurrent-claim",
            concurrentStartedAt,
            "token-concurrent-a"
          ),
          claimAuditTracking(
            workerB,
            "job-concurrent-claim",
            concurrentStartedAt,
            "token-concurrent-b"
          ),
        ]);
        expect([claimA, claimB].filter(Boolean)).toHaveLength(1);
        const winner = claimA ? database : workerB;
        await winner.$executeRawUnsafe(
          `INSERT INTO "ReconcileWriterEntry" ("worker") VALUES ($1)`,
          claimA ? "worker-a" : "worker-b"
        );
        const writerRows = await database.$queryRawUnsafe<
          Array<{ count: bigint }>
        >(`SELECT count(*)::bigint AS count FROM "ReconcileWriterEntry"`);
        expect(Number(writerRows[0].count)).toBe(1);

        const tokenA = await claimAuditTracking(
          database,
          "job-stale-claim",
          concurrentStartedAt,
          "token-stale-a"
        );
        expect(tokenA).toBe("token-stale-a");
        await expect(
          claimAuditTracking(
            workerB,
            "job-stale-claim",
            new Date(concurrentStartedAt.getTime() + 9 * 60 * 1000),
            "token-too-early"
          )
        ).resolves.toBeNull();
        const tokenB = await claimAuditTracking(
          workerB,
          "job-stale-claim",
          new Date(concurrentStartedAt.getTime() + 11 * 60 * 1000),
          "token-stale-b"
        );
        expect(tokenB).toBe("token-stale-b");
        await expect(
          finalizeAuditTracking(
            database,
            "job-stale-claim",
            tokenA as string,
            "completed"
          )
        ).resolves.toBe(0);
        await expect(
          finalizeAuditTracking(
            workerB,
            "job-stale-claim",
            tokenB as string,
            "completed"
          )
        ).resolves.toBe(1);
        const markerRows = await database.$queryRawUnsafe<
          Array<{ postprocessing: Record<string, unknown> }>
        >(
          `SELECT "postprocessing" FROM "AuditJob" WHERE "id" = 'job-stale-claim'`
        );
        expect(markerRows[0].postprocessing).toMatchObject({
          tracking: "completed",
        });
        expect(markerRows[0].postprocessing).toMatchObject({
          trackingReconcileToken: null,
        });
      } finally {
        await workerB.$disconnect();
      }
      const completedAt = new Date("2026-10-04T00:00:00.000Z");
      const responses = [
        {
          engineId: "naver-briefing" as const,
          rawResponse: "provider result",
          brandMentioned: false,
          mentionPosition: 1,
          mentionListSize: 3,
          sentiment: "neutral" as const,
          shareOfVoice: 1,
          errorMessage: null,
          isStub: false,
          citedSources: [],
          durationMs: 1,
          usage: {
            inputTokens: 11,
            outputTokens: 7,
            costModel: "token" as const,
          },
        },
      ];
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "completedAt", "postprocessing")
         VALUES ('job-replay', 'completed', $1, '{"briefingTracking":"pending"}'::jsonb),
                ('job-replay-2', 'completed', $1, '{"briefingTracking":"pending"}'::jsonb),
                ('job-core', 'completed', $1, '{"tracking":"pending"}'::jsonb),
                ('job-core-2', 'completed', $1, '{"tracking":"pending"}'::jsonb)`,
        completedAt
      );
      const input = {
        auditJobId: "job-replay",
        trackingAxis: "briefing" as const,
        organizationId: "org-replay",
        brandId: "brand-replay",
        completedAt,
        tagged: toBriefingTaggedResponses(responses, "브랜드 효과", "ko"),
      };
      expect(await persistAuditTracking(input)).toBe("completed");
      expect(await persistAuditTracking(input)).toBe("completed");
      await Promise.all([
        persistAuditTracking(input),
        persistAuditTracking(input),
      ]);
      const conflictResponse = { ...responses[0], shareOfVoice: 0.5 };
      expect(
        await persistAuditTracking({
          ...input,
          tagged: toBriefingTaggedResponses(
            [conflictResponse],
            "브랜드 효과",
            "ko"
          ),
        })
      ).toBe("failed");
      await persistAuditTracking({
        ...input,
        auditJobId: "job-replay-2",
      });
      const coreTagged = tagCoreResponses(
        [responses],
        [{ text: "브랜드 추천", lang: "ko", kind: "brand" }]
      );
      await persistAuditTracking({
        ...input,
        auditJobId: "job-core",
        trackingAxis: "core",
        tagged: coreTagged,
      });
      await persistAuditTracking({
        ...input,
        auditJobId: "job-core",
        trackingAxis: "core",
        tagged: coreTagged,
      });
      await Promise.all([
        persistAuditTracking({
          ...input,
          auditJobId: "job-core",
          trackingAxis: "core",
          tagged: coreTagged,
        }),
        persistAuditTracking({
          ...input,
          auditJobId: "job-core",
          trackingAxis: "core",
          tagged: coreTagged,
        }),
      ]);
      await persistAuditTracking({
        ...input,
        auditJobId: "job-core-2",
        trackingAxis: "core",
        tagged: coreTagged,
      });
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing") VALUES ($1, 'completed', 'org-replay', 'brand-replay', $2, $3::jsonb, '{"tracking":"unknown"}'::jsonb)`,
        "job-reconcile",
        completedAt,
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            // Entity adjudication may make display sov=0 while the original
            // provider share remains 1. Reconcile must preserve the latter.
            sov: 0,
            trackingInputCaptured: true,
          })),
        })
      );
      await expect(reconcileAuditTracking("job-reconcile")).resolves.toBe(
        "completed"
      );
      await expect(reconcileAuditTracking("job-reconcile")).resolves.toBe(
        "skipped"
      );
      const rows = await database.$queryRawUnsafe<{ count: bigint }[]>(
        `SELECT count(*)::bigint AS count FROM "Tracking" WHERE "brandId"=$1 AND "trackedAt"=$2`,
        "brand-replay",
        completedAt
      );
      console.log(
        `Tracking row count: ${rows[0].count.toString()} (briefing/core same-run=1 each, second runs/reconcile=5)`
      );
      expect(Number(rows[0].count)).toBe(5);
      const comparable = await database.$queryRawUnsafe<
        Array<Record<string, unknown>>
      >(
        `SELECT "trackingRowKey", "rawResponse", "shareOfVoice", "inputTokens", "outputTokens", "costBasis"
         FROM "Tracking" WHERE "trackingRowKey" IN ($1, $2) ORDER BY "trackingRowKey"`,
        "job-core|core|0|naver-briefing",
        "job-reconcile|core|0|naver-briefing"
      );
      expect(comparable).toHaveLength(2);
      expect(comparable[0]).toMatchObject({
        rawResponse: "provider result",
        shareOfVoice: 1,
        inputTokens: 11,
        outputTokens: 7,
      });
      expect(comparable[1]).toMatchObject({
        rawResponse: "provider result",
        shareOfVoice: 1,
        inputTokens: 11,
        outputTokens: 7,
      });

      // Product commit succeeds, but its immediate Tracking writer never runs.
      // The durable leaf marker and captured provider payload must recover it.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ($1, 'completed', 'org-replay', 'brand-replay', $2, $3::jsonb, '{"tracking":"completed","briefing":"not_required"}'::jsonb)`,
        "job-briefing-crash",
        completedAt,
        JSON.stringify({
          briefingStatus: "processing",
          briefingAttemptId: "attempt-crash",
          metrics: { total: 7 },
          engineResponses: [],
        })
      );
      await commitBriefingResult(
        "job-briefing-crash",
        "attempt-crash",
        [
          {
            engineId: "naver-briefing",
            brandMentioned: true,
            mentionPosition: 1,
            sentiment: "neutral",
            sov: 0,
            durationMs: 1,
            isStub: false,
            errorMessage: null,
            excerpt: "provider result",
            rawResponse: "provider result",
            shareOfVoice: 1,
            usage: { inputTokens: 11, outputTokens: 7, costModel: "token" },
            trackingInputCaptured: true,
            promptIndex: 0,
            promptText: "브랜드 효과",
            promptLang: "ko",
          },
        ],
        "브랜드 효과",
        "pending"
      );
      const beforeReplay = await database.$queryRawUnsafe<
        Array<{ count: bigint }>
      >(
        `SELECT count(*)::bigint AS count FROM "Tracking" WHERE "trackingRowKey" = 'job-briefing-crash|briefing|0|naver-briefing'`
      );
      expect(Number(beforeReplay[0].count)).toBe(0);
      await expect(
        sweepAuditTrackingReconciliation(new Date("2026-10-04T00:20:00.000Z"))
      ).resolves.toMatchObject({ completed: 1, failed: 0 });
      await expect(
        reconcileBriefingTracking("job-briefing-crash")
      ).resolves.toBe("skipped");
      const recovered = await database.$queryRawUnsafe<
        Array<Record<string, unknown>>
      >(
        `SELECT "rawResponse", "shareOfVoice", "inputTokens", "outputTokens" FROM "Tracking"
         WHERE "trackingRowKey" = 'job-briefing-crash|briefing|0|naver-briefing'`
      );
      expect(recovered).toEqual([
        {
          rawResponse: "provider result",
          shareOfVoice: 1,
          inputTokens: 11,
          outputTokens: 7,
        },
      ]);
      const recoveredJob = await database.$queryRawUnsafe<
        Array<{
          result: Record<string, unknown>;
          postprocessing: Record<string, unknown>;
        }>
      >(
        `SELECT "result", "postprocessing" FROM "AuditJob" WHERE "id" = 'job-briefing-crash'`
      );
      expect(recoveredJob[0].result.metrics).toEqual({ total: 7 });
      expect(recoveredJob[0].postprocessing).toMatchObject({
        tracking: "completed",
        briefing: "not_required",
        briefingTracking: "completed",
      });

      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "result", "postprocessing") VALUES
         ('job-briefing-race', 'completed', '{"briefingStatus":"completed"}'::jsonb, '{"briefingTracking":"pending"}'::jsonb)`
      );
      const raceAt = new Date("2026-10-04T01:00:00.000Z");
      const lateWriter = await claimBriefingTracking(
        database,
        "job-briefing-race",
        raceAt,
        "late-writer"
      );
      expect(lateWriter).toBe("late-writer");
      const secondWorker = new PrismaClient({
        adapter: new PrismaPg({ connectionString, max: 1 }),
      });
      try {
        await expect(
          claimBriefingTracking(
            secondWorker,
            "job-briefing-race",
            new Date(raceAt.getTime() + 9 * 60_000),
            "too-early"
          )
        ).resolves.toBeNull();
        await expect(
          claimBriefingTracking(
            secondWorker,
            "job-briefing-race",
            new Date(raceAt.getTime() + 11 * 60_000),
            "reconciler"
          )
        ).resolves.toBe("reconciler");
        await expect(
          finalizeBriefingTracking(
            database,
            "job-briefing-race",
            "late-writer",
            "completed"
          )
        ).resolves.toBe(0);
        await expect(
          finalizeBriefingTracking(
            secondWorker,
            "job-briefing-race",
            "reconciler",
            "completed"
          )
        ).resolves.toBe(1);
      } finally {
        await secondWorker.$disconnect();
      }

      // Ten old snapshots cannot be keyed. They must not monopolize LIMIT 10
      // and prevent a newer, valid core run from ever making progress.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         SELECT 'job-terminal-' || n::text, 'completed', 'org-replay', 'brand-replay',
                $1::timestamptz - interval '1 hour' + (n || ' seconds')::interval,
                '{"engineResponses":[{"engineId":"naver-briefing","promptText":"legacy"}]}'::jsonb,
                '{"tracking":"pending"}'::jsonb
         FROM generate_series(1, 10) AS n`,
        completedAt
      );
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-after-terminals', 'completed', 'org-replay', 'brand-replay', $1, $2::jsonb, '{"tracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            trackingInputCaptured: true,
          })),
        })
      );
      const sweepAt = new Date("2026-10-04T01:00:00.000Z");
      await sweepAuditTrackingReconciliation(sweepAt);
      await sweepAuditTrackingReconciliation(sweepAt);
      const terminalStates = await database.$queryRawUnsafe<
        Array<{ state: string; count: bigint }>
      >(
        `SELECT "postprocessing"->>'tracking' AS state, count(*)::bigint AS count
         FROM "AuditJob" WHERE "id" LIKE 'job-terminal-%' GROUP BY 1`
      );
      expect(terminalStates).toEqual([{ state: "unreplayable", count: 10n }]);
      const newerState = await database.$queryRawUnsafe<
        Array<{ state: string }>
      >(
        `SELECT "postprocessing"->>'tracking' AS state FROM "AuditJob" WHERE "id" = 'job-after-terminals'`
      );
      expect(newerState).toEqual([{ state: "completed" }]);

      // Removed org and an immutable all-stub snapshot are terminal, not
      // repeatable database failures.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-removed-org', 'completed', 'org-removed', 'brand-replay', $1, $2::jsonb, '{"tracking":"pending"}'::jsonb),
                ('job-all-stub', 'completed', 'org-replay', 'brand-replay', $1, $3::jsonb, '{"tracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            trackingInputCaptured: true,
          })),
        }),
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            isStub: true,
            trackingInputCaptured: true,
          })),
        })
      );
      await expect(reconcileAuditTracking("job-removed-org")).resolves.toBe(
        "skipped"
      );
      await expect(reconcileAuditTracking("job-all-stub")).resolves.toBe(
        "skipped"
      );
      const notApplicable = await database.$queryRawUnsafe<
        Array<{ id: string; state: string }>
      >(
        `SELECT "id", "postprocessing"->>'tracking' AS state FROM "AuditJob"
         WHERE "id" IN ('job-removed-org', 'job-all-stub') ORDER BY "id"`
      );
      expect(notApplicable).toEqual([
        { id: "job-all-stub", state: "not_applicable" },
        { id: "job-removed-org", state: "not_applicable" },
      ]);

      // A missing Engine seed is potentially repairable. Retry only after
      // nextAttemptAt, and stop after the bounded third attempt.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-seed-later', 'completed', 'org-replay', 'brand-replay', $1, $2::jsonb, '{"tracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            engineId: "engine-not-seeded",
            trackingInputCaptured: true,
          })),
        })
      );
      await expect(reconcileAuditTracking("job-seed-later")).resolves.toBe(
        "failed"
      );
      await expect(reconcileAuditTracking("job-seed-later")).resolves.toBe(
        "skipped"
      );
      const retryState = await database.$queryRawUnsafe<
        Array<{ attempts: number; state: string; nextAt: string }>
      >(
        `SELECT ("postprocessing"->>'trackingReconcileAttempts')::int AS attempts,
                "postprocessing"->>'tracking' AS state,
                "postprocessing"->>'trackingNextAttemptAt' AS "nextAt"
         FROM "AuditJob" WHERE "id" = 'job-seed-later'`
      );
      expect(retryState[0]).toMatchObject({ attempts: 1, state: "unknown" });
      expect(Date.parse(retryState[0].nextAt)).toBeGreaterThan(Date.now());
      await sweepAuditTrackingReconciliation(new Date());
      const deferredRetry = await database.$queryRawUnsafe<
        Array<{ attempts: number }>
      >(
        `SELECT ("postprocessing"->>'trackingReconcileAttempts')::int AS attempts
         FROM "AuditJob" WHERE "id" = 'job-seed-later'`
      );
      expect(deferredRetry).toEqual([{ attempts: 1 }]);
      for (let attempt = 2; attempt <= 3; attempt++) {
        await database.$executeRawUnsafe(
          `UPDATE "AuditJob" SET "postprocessing" = jsonb_set("postprocessing", '{trackingNextAttemptAt}', to_jsonb('2000-01-01T00:00:00Z'::text), true)
           WHERE "id" = 'job-seed-later'`
        );
        await expect(reconcileAuditTracking("job-seed-later")).resolves.toBe(
          "failed"
        );
      }
      const exhausted = await database.$queryRawUnsafe<
        Array<{ attempts: number; state: string }>
      >(
        `SELECT ("postprocessing"->>'trackingReconcileAttempts')::int AS attempts,
                "postprocessing"->>'tracking' AS state FROM "AuditJob" WHERE "id" = 'job-seed-later'`
      );
      expect(exhausted).toEqual([{ attempts: 3, state: "retry_exhausted" }]);

      // Briefing uses the same terminal classification without touching core.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-briefing-removed-org', 'completed', 'org-removed', 'brand-replay', $1, $2::jsonb,
                 '{"tracking":"completed","briefingTracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          briefingStatus: "completed",
          briefingPrompt: "브랜드 효과",
          engineResponses: [
            {
              ...responses[0],
              trackingInputCaptured: true,
              promptIndex: 0,
              promptText: "브랜드 효과",
              promptLang: "ko",
            },
          ],
        })
      );
      await expect(
        reconcileBriefingTracking("job-briefing-removed-org")
      ).resolves.toBe("skipped");
      const briefingTerminal = await database.$queryRawUnsafe<
        Array<{ postprocessing: Record<string, unknown> }>
      >(
        `SELECT "postprocessing" FROM "AuditJob" WHERE "id" = 'job-briefing-removed-org'`
      );
      expect(briefingTerminal[0].postprocessing).toMatchObject({
        tracking: "completed",
        briefingTracking: "not_applicable",
      });

      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-malformed-core', 'completed', 'org-replay', 'brand-replay', $1,
                 '{"engineResponses":[null]}'::jsonb, '{"tracking":"pending"}'::jsonb),
                ('job-malformed-briefing', 'completed', 'org-replay', 'brand-replay', $1,
                 '{"briefingStatus":"completed","briefingPrompt":"브랜드 효과","engineResponses":[null]}'::jsonb,
                 '{"briefingTracking":"pending"}'::jsonb)`,
        completedAt
      );
      await expect(reconcileAuditTracking("job-malformed-core")).resolves.toBe(
        "skipped"
      );
      await expect(
        reconcileBriefingTracking("job-malformed-briefing")
      ).resolves.toBe("skipped");
      const malformed = await database.$queryRawUnsafe<
        Array<{ id: string; postprocessing: Record<string, unknown> }>
      >(
        `SELECT "id", "postprocessing" FROM "AuditJob" WHERE "id" LIKE 'job-malformed-%' ORDER BY "id"`
      );
      expect(malformed[0].postprocessing).toMatchObject({
        briefingTracking: "unreplayable",
      });
      expect(malformed[1].postprocessing).toMatchObject({
        tracking: "unreplayable",
      });

      // Even due legacy unknowns must not take every slot ahead of a new
      // pending run. Pending has priority, while retries remain age-bounded.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         SELECT 'job-legacy-unknown-' || n::text, 'completed', 'org-replay', 'brand-replay',
                $1::timestamptz - interval '2 hours',
                '{"engineResponses":[{"engineId":"naver-briefing","promptText":"legacy"}]}'::jsonb,
                '{"tracking":"unknown","trackingNextAttemptAt":"2000-01-01T00:00:00Z"}'::jsonb
         FROM generate_series(1, 10) AS n`,
        completedAt
      );
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-new-pending', 'completed', 'org-replay', 'brand-replay', $1, $2::jsonb, '{"tracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            trackingInputCaptured: true,
          })),
        })
      );
      await sweepAuditTrackingReconciliation(sweepAt);
      const fairState = await database.$queryRawUnsafe<
        Array<{ state: string }>
      >(
        `SELECT "postprocessing"->>'tracking' AS state FROM "AuditJob" WHERE "id" = 'job-new-pending'`
      );
      expect(fairState).toEqual([{ state: "completed" }]);

      // Simulate three workers killed after claim: no finalize call runs.
      // The following sweep must retire both axes without a fourth claim.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-killed-core', 'completed', 'org-replay', 'brand-replay', $1, $2::jsonb,
                 '{"tracking":"pending"}'::jsonb),
                ('job-killed-briefing', 'completed', 'org-replay', 'brand-replay', $1, $3::jsonb,
                 '{"tracking":"completed","briefingTracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            trackingInputCaptured: true,
          })),
        }),
        JSON.stringify({
          briefingStatus: "completed",
          briefingPrompt: "브랜드 효과",
          engineResponses: [
            {
              ...responses[0],
              trackingInputCaptured: true,
              promptIndex: 0,
              promptText: "브랜드 효과",
              promptLang: "ko",
            },
          ],
        })
      );
      const killedAt = new Date("2026-10-04T02:00:00.000Z");
      for (let attempt = 1; attempt <= 3; attempt++) {
        const claimedAt = new Date(
          killedAt.getTime() + (attempt - 1) * 11 * 60_000
        );
        await expect(
          claimAuditTracking(
            database,
            "job-killed-core",
            claimedAt,
            `killed-core-${attempt}`
          )
        ).resolves.toBe(`killed-core-${attempt}`);
        await expect(
          claimBriefingTracking(
            database,
            "job-killed-briefing",
            claimedAt,
            `killed-briefing-${attempt}`
          )
        ).resolves.toBe(`killed-briefing-${attempt}`);
      }
      // The third worker dies too. Make its lease unambiguously stale while
      // preserving the third token and attempt count.
      await database.$executeRawUnsafe(
        `UPDATE "AuditJob" SET "postprocessing" = jsonb_set("postprocessing",
           '{trackingReconcileStartedAt}', to_jsonb('2000-01-01T00:00:00Z'::text), true)
         WHERE "id" = 'job-killed-core'`
      );
      await database.$executeRawUnsafe(
        `UPDATE "AuditJob" SET "postprocessing" = jsonb_set("postprocessing",
           '{briefingTrackingReconcileStartedAt}', to_jsonb('2000-01-01T00:00:00Z'::text), true)
         WHERE "id" = 'job-killed-briefing'`
      );
      const terminalSweepAt = new Date();
      await expect(
        claimAuditTracking(
          database,
          "job-killed-core",
          terminalSweepAt,
          "forbidden-fourth-core"
        )
      ).resolves.toBeNull();
      await expect(
        claimBriefingTracking(
          database,
          "job-killed-briefing",
          terminalSweepAt,
          "forbidden-fourth-briefing"
        )
      ).resolves.toBeNull();
      await sweepAuditTrackingReconciliation(terminalSweepAt);
      const killedStates = await database.$queryRawUnsafe<
        Array<{ id: string; postprocessing: Record<string, unknown> }>
      >(
        `SELECT "id", "postprocessing" FROM "AuditJob" WHERE "id" LIKE 'job-killed-%' ORDER BY "id"`
      );
      expect(killedStates[0].postprocessing).toMatchObject({
        briefingTracking: "retry_exhausted",
        briefingTrackingReconcileAttempts: 3,
        briefingTrackingReconcileToken: null,
      });
      expect(killedStates[1].postprocessing).toMatchObject({
        tracking: "retry_exhausted",
        trackingReconcileAttempts: 3,
        trackingReconcileToken: null,
      });
      await expect(
        finalizeAuditTracking(
          database,
          "job-killed-core",
          "killed-core-3",
          "completed"
        )
      ).resolves.toBe(0);
      await expect(
        finalizeBriefingTracking(
          database,
          "job-killed-briefing",
          "killed-briefing-3",
          "completed"
        )
      ).resolves.toBe(0);
      await sweepAuditTrackingReconciliation(
        new Date(killedAt.getTime() + 44 * 60_000)
      );
      const afterSweep = await database.$queryRawUnsafe<
        Array<{ id: string; postprocessing: Record<string, unknown> }>
      >(
        `SELECT "id", "postprocessing" FROM "AuditJob" WHERE "id" LIKE 'job-killed-%' ORDER BY "id"`
      );
      expect(afterSweep).toEqual(killedStates);
      await expect(
        claimAuditTracking(
          database,
          "job-killed-core",
          new Date(killedAt.getTime() + 55 * 60_000),
          "fourth-core"
        )
      ).resolves.toBeNull();
      await expect(
        claimBriefingTracking(
          database,
          "job-killed-briefing",
          new Date(killedAt.getTime() + 55 * 60_000),
          "fourth-briefing"
        )
      ).resolves.toBeNull();

      // If the current writer commits first, the retirement CAS must lose.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "completedAt", "postprocessing")
         VALUES ('job-late-wins-core', 'completed', $1,
                 '{"tracking":"reconciling","trackingReconcileAttempts":3,
                   "trackingReconcileToken":"live-core","trackingReconcileStartedAt":"2000-01-01T00:00:00Z"}'::jsonb),
                ('job-late-wins-briefing', 'completed', $1,
                 '{"briefingTracking":"reconciling","briefingTrackingReconcileAttempts":3,
                   "briefingTrackingReconcileToken":"live-briefing","briefingTrackingReconcileStartedAt":"2000-01-01T00:00:00Z"}'::jsonb)`,
        completedAt
      );
      await expect(
        finalizeAuditTracking(
          database,
          "job-late-wins-core",
          "live-core",
          "completed"
        )
      ).resolves.toBe(1);
      await expect(
        finalizeBriefingTracking(
          database,
          "job-late-wins-briefing",
          "live-briefing",
          "completed"
        )
      ).resolves.toBe(1);
      await expect(
        retireExhaustedTrackingClaim(
          database,
          "job-late-wins-core",
          "tracking",
          "reconciling",
          "live-core",
          terminalSweepAt
        )
      ).resolves.toBe(0);
      await expect(
        retireExhaustedTrackingClaim(
          database,
          "job-late-wins-briefing",
          "briefingTracking",
          "reconciling",
          "live-briefing",
          terminalSweepAt
        )
      ).resolves.toBe(0);
      const lateWins = await database.$queryRawUnsafe<
        Array<{ id: string; postprocessing: Record<string, unknown> }>
      >(
        `SELECT "id", "postprocessing" FROM "AuditJob" WHERE "id" LIKE 'job-late-wins-%' ORDER BY "id"`
      );
      expect(lateWins[0].postprocessing).toMatchObject({
        briefingTracking: "completed",
      });
      expect(lateWins[1].postprocessing).toMatchObject({
        tracking: "completed",
      });

      // RED: one missing Engine seed must not turn a two-key audit into a
      // successful one-row Tracking write.
      await database.$executeRawUnsafe(
        `INSERT INTO "Engine" ("id", "name", "provider", "language")
         VALUES ('chatgpt', 'ChatGPT', 'naver', 'ko')`
      );
      const planned = tagCoreResponses(
        [
          [
            { ...responses[0], engineId: "chatgpt" },
            {
              ...responses[0],
              engineId: "gemini",
              rawResponse: "gemini result",
            },
          ],
        ],
        [{ text: "브랜드 추천", lang: "ko", kind: "brand" }]
      );
      const snapshot = JSON.stringify({
        engineResponses: planned.map((row) => ({
          ...row,
          trackingInputCaptured: true,
        })),
      });
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-two-engines-one-seed', 'completed', 'org-replay', 'brand-replay',
                 $1, $2::jsonb, '{"tracking":"pending"}'::jsonb)`,
        completedAt,
        snapshot
      );
      expect
        .soft(await reconcileAuditTracking("job-two-engines-one-seed"))
        .toBe("failed");
      const subset = await database.$queryRawUnsafe<
        Array<{ count: bigint; state: string }>
      >(
        `SELECT count(t."id")::bigint AS count, j."postprocessing"->>'tracking' AS state
         FROM "AuditJob" j LEFT JOIN "Tracking" t
           ON t."trackingRowKey" IN ('job-two-engines-one-seed|core|0|chatgpt',
                                      'job-two-engines-one-seed|core|0|gemini')
         WHERE j."id" = 'job-two-engines-one-seed'
         GROUP BY j."postprocessing"`
      );
      expect.soft(subset).toEqual([{ count: 0n, state: "unknown" }]);

      // The immutable manifest must be committed in the same transaction as
      // the complete keyed row set, not inferred later from current Engines.
      await database.$executeRawUnsafe(
        `INSERT INTO "Engine" ("id", "name", "provider", "language")
         VALUES ('gemini', 'Gemini', 'naver', 'ko')`
      );
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-manifest-complete', 'completed', 'org-replay', 'brand-replay',
                 $1, $2::jsonb, '{"tracking":"pending"}'::jsonb),
                ('job-manifest-partial', 'completed', 'org-replay', 'brand-replay',
                 $1, $2::jsonb, '{"tracking":"pending"}'::jsonb)`,
        completedAt,
        snapshot
      );
      const completeInput = {
        ...input,
        auditJobId: "job-manifest-complete",
        trackingAxis: "core" as const,
        tagged: planned,
      };
      expect(await persistAuditTracking(completeInput)).toBe("completed");
      expect(
        await persistAuditTracking({
          ...completeInput,
          auditJobId: "job-manifest-partial",
          tagged: planned,
        })
      ).toBe("completed");
      const completeCoreRows = await database.$queryRawUnsafe<
        Array<{ count: bigint }>
      >(
        `SELECT count(*)::bigint AS count FROM "Tracking"
         WHERE "trackingRowKey" LIKE 'job-manifest-complete|core|%'`
      );
      expect.soft(completeCoreRows).toEqual([{ count: 2n }]);
      const expectedManifest = {
        v: 1,
        brandId: "brand-replay",
        trackedAt: completedAt.toISOString(),
        keys: [
          "job-manifest-complete|core|0|chatgpt",
          "job-manifest-complete|core|0|gemini",
        ],
      };
      const completeBeforeCrash = await database.$queryRawUnsafe<
        Array<{ postprocessing: Record<string, unknown> }>
      >(
        `SELECT "postprocessing" FROM "AuditJob" WHERE "id" = 'job-manifest-complete'`
      );
      expect.soft(completeBeforeCrash[0].postprocessing).toMatchObject({
        trackingManifest: expectedManifest,
      });
      // Simulate a lost row after a genuine two-key manifest commit.
      await database.$executeRawUnsafe(
        `DELETE FROM "Tracking" WHERE "trackingRowKey" = 'job-manifest-partial|core|0|gemini'`
      );
      await database.$executeRawUnsafe(
        `UPDATE "AuditJob"
         SET "postprocessing" = "postprocessing" ||
           jsonb_build_object('tracking', 'reconciling',
                              'trackingReconcileAttempts', 3,
                              'trackingReconcileToken', 'third',
                              'trackingReconcileStartedAt', '2000-01-01T00:00:00Z')
         WHERE "id" = $1`,
        "job-manifest-complete"
      );
      await database.$executeRawUnsafe(
        `UPDATE "AuditJob"
         SET "postprocessing" = "postprocessing" ||
           jsonb_build_object('tracking', 'reconciling',
                              'trackingReconcileAttempts', 3,
                              'trackingReconcileToken', 'third',
                              'trackingReconcileStartedAt', '2000-01-01T00:00:00Z')
         WHERE "id" = $1`,
        "job-manifest-partial"
      );
      await reconcileAuditTracking("job-manifest-complete");
      await reconcileAuditTracking("job-manifest-partial");
      const manifestStates = await database.$queryRawUnsafe<
        Array<{ id: string; state: string }>
      >(
        `SELECT "id", "postprocessing"->>'tracking' AS state
         FROM "AuditJob" WHERE "id" LIKE 'job-manifest-%' ORDER BY "id"`
      );
      expect.soft(manifestStates).toEqual([
        { id: "job-manifest-complete", state: "completed" },
        { id: "job-manifest-partial", state: "retry_exhausted" },
      ]);

      // The briefing axis owns a different manifest and cannot alter core.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-manifest-briefing', 'completed', 'org-replay', 'brand-replay',
                 $1, $2::jsonb, '{"tracking":"completed","briefingTracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          briefingStatus: "completed",
          briefingPrompt: "브랜드 효과",
          engineResponses: [
            {
              ...responses[0],
              trackingInputCaptured: true,
              promptIndex: 0,
              promptText: "브랜드 효과",
              promptLang: "ko",
            },
          ],
        })
      );
      expect(
        await persistAuditTracking({
          ...input,
          auditJobId: "job-manifest-briefing",
        })
      ).toBe("completed");
      await database.$executeRawUnsafe(
        `UPDATE "AuditJob" SET "postprocessing" = "postprocessing" ||
           '{"briefingTracking":"reconciling","briefingTrackingReconcileAttempts":3,
             "briefingTrackingReconcileToken":"third",
             "briefingTrackingReconcileStartedAt":"2000-01-01T00:00:00Z"}'::jsonb
         WHERE "id" = 'job-manifest-briefing'`
      );
      await reconcileBriefingTracking("job-manifest-briefing");
      const briefingManifest = await database.$queryRawUnsafe<
        Array<{ postprocessing: Record<string, unknown> }>
      >(
        `SELECT "postprocessing" FROM "AuditJob" WHERE "id" = 'job-manifest-briefing'`
      );
      expect.soft(briefingManifest[0].postprocessing).toMatchObject({
        tracking: "completed",
        briefingTracking: "completed",
        briefingTrackingManifest: {
          v: 1,
          brandId: "brand-replay",
          trackedAt: completedAt.toISOString(),
          keys: ["job-manifest-briefing|briefing|0|naver-briefing"],
        },
      });

      // A committed briefing manifest without its sole row is 0/1, not complete.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-manifest-briefing-missing', 'completed', 'org-replay', 'brand-replay',
                 $1, $2::jsonb, '{"tracking":"completed","briefingTracking":"pending"}'::jsonb)`,
        completedAt,
        JSON.stringify({
          briefingStatus: "completed",
          briefingPrompt: "브랜드 효과",
          engineResponses: [
            {
              ...responses[0],
              trackingInputCaptured: true,
              promptIndex: 0,
              promptText: "브랜드 효과",
              promptLang: "ko",
            },
          ],
        })
      );
      expect(
        await persistAuditTracking({
          ...input,
          auditJobId: "job-manifest-briefing-missing",
        })
      ).toBe("completed");
      const beforeMissingBriefing = await database.$queryRawUnsafe<
        Array<{ count: bigint }>
      >(
        `SELECT count(*)::bigint AS count FROM "Tracking"
         WHERE "trackingRowKey" = 'job-manifest-briefing-missing|briefing|0|naver-briefing'`
      );
      expect.soft(beforeMissingBriefing).toEqual([{ count: 1n }]);
      await database.$executeRawUnsafe(
        `DELETE FROM "Tracking"
         WHERE "trackingRowKey" = 'job-manifest-briefing-missing|briefing|0|naver-briefing'`
      );
      await database.$executeRawUnsafe(
        `UPDATE "AuditJob" SET "postprocessing" = "postprocessing" ||
           '{"briefingTracking":"reconciling","briefingTrackingReconcileAttempts":3,
             "briefingTrackingReconcileToken":"third",
             "briefingTrackingReconcileStartedAt":"2000-01-01T00:00:00Z"}'::jsonb
         WHERE "id" = 'job-manifest-briefing-missing'`
      );
      await reconcileBriefingTracking("job-manifest-briefing-missing");
      const missingBriefing = await database.$queryRawUnsafe<
        Array<{ count: bigint; postprocessing: Record<string, unknown> }>
      >(
        `SELECT count(t."id")::bigint AS count, j."postprocessing"
         FROM "AuditJob" j LEFT JOIN "Tracking" t
           ON t."trackingRowKey" = 'job-manifest-briefing-missing|briefing|0|naver-briefing'
         WHERE j."id" = 'job-manifest-briefing-missing'
         GROUP BY j."postprocessing"`
      );
      expect.soft(missingBriefing).toEqual([
        {
          count: 0n,
          postprocessing: expect.objectContaining({
            tracking: "completed",
            briefingTracking: "retry_exhausted",
            briefingTrackingManifest: {
              v: 1,
              brandId: "brand-replay",
              trackedAt: completedAt.toISOString(),
              keys: ["job-manifest-briefing-missing|briefing|0|naver-briefing"],
            },
          }),
        },
      ]);

      // A stale writer with the wrong claim token must roll its rows back.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ('job-manifest-lost-token', 'completed', 'org-replay', 'brand-replay',
                 $1, $2::jsonb,
                 '{"tracking":"reconciling","trackingReconcileToken":"winner"}'::jsonb)`,
        completedAt,
        snapshot
      );
      expect(
        await persistAuditTracking({
          ...completeInput,
          auditJobId: "job-manifest-lost-token",
          trackingClaimToken: "loser",
        })
      ).toBe("failed");
      const lostToken = await database.$queryRawUnsafe<
        Array<{ count: bigint; postprocessing: Record<string, unknown> }>
      >(
        `SELECT count(t."id")::bigint AS count, j."postprocessing"
         FROM "AuditJob" j LEFT JOIN "Tracking" t
           ON t."trackingRowKey" LIKE 'job-manifest-lost-token|core|%'
         WHERE j."id" = 'job-manifest-lost-token'
         GROUP BY j."postprocessing"`
      );
      expect.soft(lostToken).toEqual([
        {
          count: 0n,
          postprocessing: {
            tracking: "reconciling",
            trackingReconcileToken: "winner",
          },
        },
      ]);
    } finally {
      await database.$disconnect();
    }
  }, 60_000);
});
