/** @vitest-environment node */

import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { PrismaPg } from "@repo/database/node_modules/@prisma/adapter-pg/dist/index.mjs";
import { PrismaClient } from "@repo/database/generated/client";
import { toBriefingTaggedResponses } from "@repo/audit/briefing-tracking";
import { tagCoreResponses } from "@repo/audit/tracking";
import {
  claimAuditTracking,
  finalizeAuditTracking,
  reconcileAuditTracking,
} from "@repo/audit/reconcile-audit-tracking";
import {
  claimBriefingTracking,
  finalizeBriefingTracking,
  reconcileBriefingTracking,
} from "@repo/audit/reconcile-briefing-tracking";
import { sweepAuditTrackingReconciliation } from "@repo/audit/sweep-audit-tracking";
import { afterAll, describe, expect, it, vi } from "vitest";

const state = vi.hoisted(() => ({ database: null as unknown }));
vi.mock("@repo/database", () => ({
  get database() {
    return state.database;
  },
}));
vi.mock("@repo/observability/log", () => ({
  log: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));
vi.mock("@repo/ai/lib/engines", () => ({
  costOf: () => ({ krw: 0, basis: "test" }),
}));

const { persistAuditTracking } = await import("@repo/audit/tracking");
const { commitBriefingResult } = await import("@repo/audit/briefing-runner");
const tempDir = mkdtempSync("/tmp/findable-tracking-prisma-");
const socketDir = join(tempDir, "socket");
const port = 15732 + Math.floor(Math.random() * 100);
const role = execFileSync("id", ["-un"], { encoding: "utf8" }).trim();
const connectionString = `postgresql://${role}@127.0.0.1:${port}/postgres?application_name=findable_tracking_prisma`;
let serverStarted = false;

function run(command: string, args: string[]) {
  const result = spawnSync(command, args, { encoding: "utf8" });
  if (result.status !== 0) throw new Error(`${command} failed: ${result.stderr || result.stdout}`);
}

function startDatabase() {
  run("initdb", ["-D", tempDir, "-A", "trust", "--no-locale"]);
  mkdirSync(socketDir);
  run("pg_ctl", ["-D", tempDir, "-o", `-p ${port} -k ${socketDir}`, "-l", join(tempDir, "postgres.log"), "start"]);
  serverStarted = true;
  const deadline = Date.now() + 5_000;
  while (Date.now() < deadline) {
    if (spawnSync("pg_isready", ["-h", "127.0.0.1", "-p", String(port)]).status === 0) return;
  }
  throw new Error("PostgreSQL readiness timed out");
}

afterAll(() => {
  if (serverStarted) {
    spawnSync("pg_ctl", ["-D", tempDir, "-o", `-p ${port} -k ${socketDir}`, "stop", "-m", "immediate"], { stdio: "ignore" });
  }
  rmSync(tempDir, { recursive: true, force: true });
});

describe("product Tracking replay through PrismaPg", () => {
  it("GREEN characterization: replay and contention converge to one row per run key", async () => {
    startDatabase();
    const database = new PrismaClient({ adapter: new PrismaPg({ connectionString, max: 1 }) });
    state.database = database;
    try {
      await database.$executeRawUnsafe(`
        CREATE TYPE "PromptLanguage" AS ENUM ('ko', 'en');
        CREATE TYPE "PromptCategory" AS ENUM ('custom');
        CREATE TYPE "EngineProvider" AS ENUM ('naver');
        CREATE TYPE "EngineLanguage" AS ENUM ('ko');
        CREATE TYPE "Sentiment" AS ENUM ('positive', 'neutral', 'negative');
        CREATE TABLE "Organization" ("id" text PRIMARY KEY);
        CREATE TABLE "Brand" ("id" text PRIMARY KEY, "organizationId" text NOT NULL);
        CREATE TABLE "Engine" ("id" text PRIMARY KEY, "name" text NOT NULL, "provider" "EngineProvider" NOT NULL, "language" "EngineLanguage" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "ordering" integer NOT NULL DEFAULT 0);
        CREATE TABLE "Prompt" ("id" text PRIMARY KEY, "brandId" text NOT NULL, "text" text NOT NULL, "language" "PromptLanguage" NOT NULL, "category" "PromptCategory", "isAutoGenerated" boolean NOT NULL DEFAULT false, "createdAt" timestamptz NOT NULL DEFAULT now(), UNIQUE ("brandId", "text"));
        CREATE TABLE "Tracking" ("id" text PRIMARY KEY, "brandId" text NOT NULL, "promptId" text NOT NULL, "engineId" text NOT NULL, "rawResponse" text, "brandMentioned" boolean NOT NULL DEFAULT false, "mentionPosition" integer, "mentionListSize" integer, "sentiment" "Sentiment", "citedSources" jsonb NOT NULL DEFAULT '[]', "shareOfVoice" double precision, "errorMessage" text, "trackedAt" timestamptz NOT NULL DEFAULT now(), "inputTokens" integer, "outputTokens" integer, "costKrw" double precision, "costBasis" text);
        CREATE TABLE "AuditJob" ("id" text PRIMARY KEY, "status" text NOT NULL, "organizationId" text, "brandId" text, "completedAt" timestamptz, "result" jsonb, "postprocessing" jsonb);
        CREATE TABLE "ReconcileWriterEntry" ("worker" text PRIMARY KEY);
        INSERT INTO "Organization" ("id") VALUES ('org-replay');
        INSERT INTO "Brand" ("id", "organizationId") VALUES ('brand-replay', 'org-replay');
        INSERT INTO "Engine" ("id", "name", "provider", "language") VALUES ('naver-briefing', 'Naver Briefing', 'naver', 'ko');
      `);
      const migrationPath = fileURLToPath(
        new URL(
          "../../../packages/database/prisma/migrations/20261004_tracking_row_key/migration.sql",
          import.meta.url
        )
      );
      await database.$executeRawUnsafe(readFileSync(migrationPath, "utf8"));
      const workerB = new PrismaClient({ adapter: new PrismaPg({ connectionString, max: 1 }) });
      try {
        const concurrentStartedAt = new Date("2026-10-04T01:00:00.000Z");
        await database.$executeRawUnsafe(
          `INSERT INTO "AuditJob" ("id", "status", "postprocessing") VALUES ('job-concurrent-claim', 'completed', '{"tracking":"unknown"}'::jsonb), ('job-stale-claim', 'completed', '{"tracking":"unknown"}'::jsonb)`
        );
        const [claimA, claimB] = await Promise.all([
          claimAuditTracking(database, "job-concurrent-claim", concurrentStartedAt, "token-concurrent-a"),
          claimAuditTracking(workerB, "job-concurrent-claim", concurrentStartedAt, "token-concurrent-b"),
        ]);
        expect([claimA, claimB].filter(Boolean)).toHaveLength(1);
        const winner = claimA ? database : workerB;
        await winner.$executeRawUnsafe(
          `INSERT INTO "ReconcileWriterEntry" ("worker") VALUES ($1)`,
          claimA ? "worker-a" : "worker-b"
        );
        const writerRows = await database.$queryRawUnsafe<Array<{ count: bigint }>>(
          `SELECT count(*)::bigint AS count FROM "ReconcileWriterEntry"`
        );
        expect(Number(writerRows[0].count)).toBe(1);

        const tokenA = await claimAuditTracking(
          database,
          "job-stale-claim",
          concurrentStartedAt,
          "token-stale-a"
        );
        expect(tokenA).toBe("token-stale-a");
        await expect(
          claimAuditTracking(
            workerB,
            "job-stale-claim",
            new Date(concurrentStartedAt.getTime() + 9 * 60 * 1000),
            "token-too-early"
          )
        ).resolves.toBeNull();
        const tokenB = await claimAuditTracking(
          workerB,
          "job-stale-claim",
          new Date(concurrentStartedAt.getTime() + 11 * 60 * 1000),
          "token-stale-b"
        );
        expect(tokenB).toBe("token-stale-b");
        await expect(
          finalizeAuditTracking(database, "job-stale-claim", tokenA as string, "completed")
        ).resolves.toBe(0);
        await expect(
          finalizeAuditTracking(workerB, "job-stale-claim", tokenB as string, "completed")
        ).resolves.toBe(1);
        const markerRows = await database.$queryRawUnsafe<Array<{ postprocessing: Record<string, unknown> }>>(
          `SELECT "postprocessing" FROM "AuditJob" WHERE "id" = 'job-stale-claim'`
        );
        expect(markerRows[0].postprocessing).toMatchObject({ tracking: "completed" });
        expect(markerRows[0].postprocessing).toMatchObject({ trackingReconcileToken: null });
      } finally {
        await workerB.$disconnect();
      }
      const completedAt = new Date("2026-10-04T00:00:00.000Z");
      const responses = [{ engineId: "naver-briefing" as const, rawResponse: "provider result", brandMentioned: false, mentionPosition: 1, mentionListSize: 3, sentiment: "neutral" as const, shareOfVoice: 1, errorMessage: null, isStub: false, citedSources: [], durationMs: 1, usage: { inputTokens: 11, outputTokens: 7, costModel: "token" as const } }];
      const input = {
        auditJobId: "job-replay",
        trackingAxis: "briefing" as const,
        organizationId: "org-replay",
        brandId: "brand-replay",
        completedAt,
        tagged: toBriefingTaggedResponses(responses, "브랜드 효과", "ko"),
      };
      expect(await persistAuditTracking(input)).toBe("completed");
      expect(await persistAuditTracking(input)).toBe("completed");
      await Promise.all([persistAuditTracking(input), persistAuditTracking(input)]);
      const conflictResponse = { ...responses[0], shareOfVoice: 0.5 };
      expect(
        await persistAuditTracking({
          ...input,
          tagged: toBriefingTaggedResponses([conflictResponse], "브랜드 효과", "ko"),
        })
      ).toBe("failed");
      await persistAuditTracking({
        ...input,
        auditJobId: "job-replay-2",
      });
      const coreTagged = tagCoreResponses(
        [responses],
        [{ text: "브랜드 추천", lang: "ko", kind: "brand" }]
      );
      await persistAuditTracking({
        ...input,
        auditJobId: "job-core",
        trackingAxis: "core",
        tagged: coreTagged,
      });
      await persistAuditTracking({ ...input, auditJobId: "job-core", trackingAxis: "core", tagged: coreTagged });
      await Promise.all([
        persistAuditTracking({ ...input, auditJobId: "job-core", trackingAxis: "core", tagged: coreTagged }),
        persistAuditTracking({ ...input, auditJobId: "job-core", trackingAxis: "core", tagged: coreTagged }),
      ]);
      await persistAuditTracking({ ...input, auditJobId: "job-core-2", trackingAxis: "core", tagged: coreTagged });
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing") VALUES ($1, 'completed', 'org-replay', 'brand-replay', $2, $3::jsonb, '{"tracking":"unknown"}'::jsonb)`,
        "job-reconcile",
        completedAt,
        JSON.stringify({
          engineResponses: coreTagged.map((row) => ({
            ...row,
            // Entity adjudication may make display sov=0 while the original
            // provider share remains 1. Reconcile must preserve the latter.
            sov: 0,
            trackingInputCaptured: true,
          })),
        })
      );
      await expect(reconcileAuditTracking("job-reconcile")).resolves.toBe("completed");
      await expect(reconcileAuditTracking("job-reconcile")).resolves.toBe("skipped");
      const rows = await database.$queryRawUnsafe<{ count: bigint }[]>(`SELECT count(*)::bigint AS count FROM "Tracking" WHERE "brandId"=$1 AND "trackedAt"=$2`, "brand-replay", completedAt);
      console.log(`Tracking row count: ${rows[0].count.toString()} (briefing/core same-run=1 each, second runs/reconcile=5)`);
      expect(Number(rows[0].count)).toBe(5);
      const comparable = await database.$queryRawUnsafe<Array<Record<string, unknown>>>(
        `SELECT "trackingRowKey", "rawResponse", "shareOfVoice", "inputTokens", "outputTokens", "costBasis"
         FROM "Tracking" WHERE "trackingRowKey" IN ($1, $2) ORDER BY "trackingRowKey"`,
        "job-core|core|0|naver-briefing",
        "job-reconcile|core|0|naver-briefing"
      );
      expect(comparable).toHaveLength(2);
      expect(comparable[0]).toMatchObject({ rawResponse: "provider result", shareOfVoice: 1, inputTokens: 11, outputTokens: 7 });
      expect(comparable[1]).toMatchObject({ rawResponse: "provider result", shareOfVoice: 1, inputTokens: 11, outputTokens: 7 });

      // Product commit succeeds, but its immediate Tracking writer never runs.
      // The durable leaf marker and captured provider payload must recover it.
      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "organizationId", "brandId", "completedAt", "result", "postprocessing")
         VALUES ($1, 'completed', 'org-replay', 'brand-replay', $2, $3::jsonb, '{"tracking":"completed","briefing":"not_required"}'::jsonb)`,
        "job-briefing-crash",
        completedAt,
        JSON.stringify({
          briefingStatus: "processing",
          briefingAttemptId: "attempt-crash",
          metrics: { total: 7 },
          engineResponses: [],
        })
      );
      await commitBriefingResult("job-briefing-crash", "attempt-crash", [{
        engineId: "naver-briefing",
        brandMentioned: true,
        mentionPosition: 1,
        sentiment: "neutral",
        sov: 0,
        durationMs: 1,
        isStub: false,
        errorMessage: null,
        excerpt: "provider result",
        rawResponse: "provider result",
        shareOfVoice: 1,
        usage: { inputTokens: 11, outputTokens: 7, costModel: "token" },
        trackingInputCaptured: true,
        promptIndex: 0,
        promptText: "브랜드 효과",
        promptLang: "ko",
      }], "브랜드 효과", "pending");
      const beforeReplay = await database.$queryRawUnsafe<Array<{ count: bigint }>>(
        `SELECT count(*)::bigint AS count FROM "Tracking" WHERE "trackingRowKey" = 'job-briefing-crash|briefing|0|naver-briefing'`
      );
      expect(Number(beforeReplay[0].count)).toBe(0);
      await expect(sweepAuditTrackingReconciliation(new Date("2026-10-04T00:20:00.000Z")))
        .resolves.toMatchObject({ completed: 1, failed: 0 });
      await expect(reconcileBriefingTracking("job-briefing-crash")).resolves.toBe("skipped");
      const recovered = await database.$queryRawUnsafe<Array<Record<string, unknown>>>(
        `SELECT "rawResponse", "shareOfVoice", "inputTokens", "outputTokens" FROM "Tracking"
         WHERE "trackingRowKey" = 'job-briefing-crash|briefing|0|naver-briefing'`
      );
      expect(recovered).toEqual([{ rawResponse: "provider result", shareOfVoice: 1, inputTokens: 11, outputTokens: 7 }]);
      const recoveredJob = await database.$queryRawUnsafe<Array<{ result: Record<string, unknown>; postprocessing: Record<string, unknown> }>>(
        `SELECT "result", "postprocessing" FROM "AuditJob" WHERE "id" = 'job-briefing-crash'`
      );
      expect(recoveredJob[0].result.metrics).toEqual({ total: 7 });
      expect(recoveredJob[0].postprocessing).toMatchObject({ tracking: "completed", briefing: "not_required", briefingTracking: "completed" });

      await database.$executeRawUnsafe(
        `INSERT INTO "AuditJob" ("id", "status", "result", "postprocessing") VALUES
         ('job-briefing-race', 'completed', '{"briefingStatus":"completed"}'::jsonb, '{"briefingTracking":"pending"}'::jsonb)`
      );
      const raceAt = new Date("2026-10-04T01:00:00.000Z");
      const lateWriter = await claimBriefingTracking(database, "job-briefing-race", raceAt, "late-writer");
      expect(lateWriter).toBe("late-writer");
      const secondWorker = new PrismaClient({ adapter: new PrismaPg({ connectionString, max: 1 }) });
      try {
        await expect(claimBriefingTracking(secondWorker, "job-briefing-race", new Date(raceAt.getTime() + 9 * 60_000), "too-early")).resolves.toBeNull();
        await expect(claimBriefingTracking(secondWorker, "job-briefing-race", new Date(raceAt.getTime() + 11 * 60_000), "reconciler")).resolves.toBe("reconciler");
        await expect(finalizeBriefingTracking(database, "job-briefing-race", "late-writer", "completed")).resolves.toBe(0);
        await expect(finalizeBriefingTracking(secondWorker, "job-briefing-race", "reconciler", "completed")).resolves.toBe(1);
      } finally {
        await secondWorker.$disconnect();
      }
    } finally {
      await database.$disconnect();
    }
  }, 60_000);
});
