import { database } from "@repo/database";
import { ArrowLeftIcon } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireOrg } from "@/lib/db/scoped";
import { dateLocaleFor, getAppDictionary, getAppLocale } from "@/lib/i18n";
import { Header } from "../../components/header";
import { isPromptId } from "./prompt-id";
import { responseVerdict } from "./response-verdict";

export const generateMetadata = async (): Promise<Metadata> => ({
  title: (await getAppDictionary()).promptResponses.metaTitle,
});

export default async function PromptResponsesPage({
  params,
}: {
  params: Promise<{ promptId: string }>;
}) {
  const { promptId } = await params;
  if (!isPromptId(promptId)) {
    notFound();
  }
  const orgId = await requireOrg();
  const [dict, locale] = await Promise.all([
    getAppDictionary(),
    getAppLocale(),
  ]);
  const t = dict.promptResponses;
  // Prompt에는 orgId가 없으므로 브랜드 소유권을 반드시 관계 필터로 확인한다.
  const prompt = await database.prompt.findFirst({
    where: { id: promptId, brand: { organizationId: orgId } },
    select: {
      id: true,
      brandId: true,
      text: true,
      isAutoGenerated: true,
      brand: { select: { name: true, domain: true } },
    },
  });
  if (!prompt) {
    notFound();
  }
  const responses = await database.tracking.findMany({
    where: { promptId, brand: { organizationId: orgId } },
    orderBy: { trackedAt: "desc" },
    take: 70,
    select: {
      id: true,
      rawResponse: true,
      brandMentioned: true,
      mentionPosition: true,
      sentiment: true,
      errorMessage: true,
      trackedAt: true,
      engine: { select: { name: true } },
    },
  });

  return (
    <>
      {/* 전역 헤더 지표는 조직의 가장 최근 브랜드 기준이라 이 질문의 브랜드와 다를 수 있다. */}
      <Header
        page={t.headerTitle}
        pages={["Findable", dict.promptsPage.title]}
        showMetric={false}
      />
      <main className="flex flex-1 flex-col gap-6 p-6 pt-2">
        <div className="flex flex-wrap items-center gap-4 text-sm">
          <Link
            className="inline-flex items-center gap-1 text-[color:var(--findable-ink-subtle,#8a8f98)] hover:text-[color:var(--findable-primary,#ff7a4d)]"
            href="/prompts"
          >
            <ArrowLeftIcon className="size-4" /> {t.backToPrompts}
          </Link>
          <Link
            className="text-[color:var(--findable-primary,#ff7a4d)] underline-offset-4 hover:underline"
            href={`/?brand=${prompt.brandId}#tracked-prompts`}
          >
            {t.viewScoreboard}
          </Link>
        </div>

        <header className="rounded-2xl border border-[color:var(--findable-hairline,#23252a)] bg-[color:var(--findable-surface-1,#0f1011)] p-6 sm:p-8">
          <p className="font-medium text-[color:var(--findable-primary,#ff7a4d)] text-xs uppercase tracking-[0.16em]">
            {t.eyebrow}
          </p>
          <h1 className="mt-3 max-w-3xl font-semibold text-2xl text-[color:var(--findable-ink,#f7f8f8)] leading-snug sm:text-3xl">
            {prompt.text}
          </h1>
          <p className="mt-3 text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
            {prompt.brand.name} · {prompt.brand.domain} ·{" "}
            {prompt.isAutoGenerated ? t.mine : t.default}
          </p>
          <p className="mt-4 max-w-3xl text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs leading-5">
            {t.noteBefore}{" "}
            <Link className="underline" href="/history">
              {t.noteLink}
            </Link>
            {t.noteAfter}
          </p>
        </header>

        {responses.length === 0 ? (
          <section className="rounded-xl border border-[color:var(--findable-hairline,#23252a)] border-dashed p-6 text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
            {t.empty}
          </section>
        ) : (
          <section aria-label={t.sectionLabel} className="space-y-3">
            <p className="text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs">
              {t.count.replace("{n}", String(responses.length))}
            </p>
            {responses.map((response, index) => (
              <details
                className="group overflow-hidden rounded-xl border border-[color:var(--findable-hairline,#23252a)] bg-[color:var(--findable-surface-1,#0f1011)]"
                key={response.id}
                open={index === 0}
              >
                <summary className="flex cursor-pointer list-none flex-wrap items-center gap-3 px-5 py-4 hover:bg-white/[0.025]">
                  <span className="font-medium text-[color:var(--findable-ink,#f7f8f8)] text-sm">
                    {response.engine.name}
                  </span>
                  <span className={responseVerdict(response, t).tone}>
                    {responseVerdict(response, t).label}
                  </span>
                  <time
                    className="ml-auto text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs"
                    dateTime={response.trackedAt.toISOString()}
                  >
                    {response.trackedAt.toLocaleString(dateLocaleFor(locale), {
                      timeZone: "Asia/Seoul",
                    })}
                  </time>
                </summary>
                <div className="border-[color:var(--findable-hairline,#23252a)] border-t px-5 py-5">
                  {response.rawResponse ? (
                    <div className="whitespace-pre-wrap break-words text-[color:var(--findable-ink-muted,#d0d6e0)] text-sm leading-7">
                      {response.rawResponse}
                    </div>
                  ) : (
                    <p className="text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
                      {t.noRaw}
                    </p>
                  )}
                  {!response.errorMessage && response.mentionPosition ? (
                    <p className="mt-4 text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs">
                      {t.legacyRank.replace(
                        "{n}",
                        String(response.mentionPosition)
                      )}
                    </p>
                  ) : null}
                </div>
              </details>
            ))}
          </section>
        )}
      </main>
    </>
  );
}
