import { database } from "@repo/database";
import { ArrowLeftIcon } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireOrg } from "@/lib/db/scoped";
import { Header } from "../../components/header";
import { isPromptId } from "./prompt-id";

export const metadata: Metadata = {
  title: "질문별 AI 답변 · Findable",
};

function responseVerdict(response: {
  brandMentioned: boolean;
  errorMessage: string | null;
}) {
  if (response.errorMessage) {
    return { label: "응답 수집 실패", tone: "text-amber-300 text-xs" };
  }
  if (response.brandMentioned) {
    return {
      label: "저장된 언급 후보 · 재확인 필요",
      tone: "text-emerald-300 text-xs",
    };
  }
  return {
    label: "저장된 판정: 해당 브랜드 미확인",
    tone: "text-[color:var(--findable-ink-subtle,#8a8f98)] text-xs",
  };
}

export default async function PromptResponsesPage({
  params,
}: {
  params: Promise<{ promptId: string }>;
}) {
  const { promptId } = await params;
  if (!isPromptId(promptId)) {
    notFound();
  }
  const orgId = await requireOrg();
  // Prompt에는 orgId가 없으므로 브랜드 소유권을 반드시 관계 필터로 확인한다.
  const prompt = await database.prompt.findFirst({
    where: { id: promptId, brand: { organizationId: orgId } },
    select: {
      id: true,
      brandId: true,
      text: true,
      isAutoGenerated: true,
      brand: { select: { name: true, domain: true } },
    },
  });
  if (!prompt) {
    notFound();
  }
  const responses = await database.tracking.findMany({
    where: { promptId, brand: { organizationId: orgId } },
    orderBy: { trackedAt: "desc" },
    take: 70,
    select: {
      id: true,
      rawResponse: true,
      brandMentioned: true,
      mentionPosition: true,
      sentiment: true,
      errorMessage: true,
      trackedAt: true,
      engine: { select: { name: true } },
    },
  });

  return (
    <>
      {/* 전역 헤더 지표는 조직의 가장 최근 브랜드 기준이라 이 질문의 브랜드와 다를 수 있다. */}
      <Header
        page="질문별 AI 답변"
        pages={["Findable", "추적 질문"]}
        showMetric={false}
      />
      <main className="flex flex-1 flex-col gap-6 p-6 pt-2">
        <div className="flex flex-wrap items-center gap-4 text-sm">
          <Link
            className="inline-flex items-center gap-1 text-[color:var(--findable-ink-subtle,#8a8f98)] hover:text-[color:var(--findable-primary,#ff7a4d)]"
            href="/prompts"
          >
            <ArrowLeftIcon className="size-4" /> 추적 질문으로
          </Link>
          <Link
            className="text-[color:var(--findable-primary,#ff7a4d)] underline-offset-4 hover:underline"
            href={`/?brand=${prompt.brandId}#tracked-prompts`}
          >
            이 브랜드의 질문별 성적 보기 ↗
          </Link>
        </div>

        <header className="rounded-2xl border border-[color:var(--findable-hairline,#23252a)] bg-[color:var(--findable-surface-1,#0f1011)] p-6 sm:p-8">
          <p className="font-medium text-[color:var(--findable-primary,#ff7a4d)] text-xs uppercase tracking-[0.16em]">
            질문별 측정 원문
          </p>
          <h1 className="mt-3 max-w-3xl font-semibold text-2xl text-[color:var(--findable-ink,#f7f8f8)] leading-snug sm:text-3xl">
            {prompt.text}
          </h1>
          <p className="mt-3 text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
            {prompt.brand.name} · {prompt.brand.domain} ·{" "}
            {prompt.isAutoGenerated ? "내가 고른 질문" : "기본 측정 질문"}
          </p>
          <p className="mt-4 max-w-3xl text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs leading-5">
            최근 최대 70개 저장된 원문의 전문입니다. 검색형 엔진은 생성형 답변
            대신 검색 결과·요약이 저장될 수 있습니다. 과거 저장 행에는 현재의
            브랜드 판별 근거가 없어 아래 표시는 확정 성적이 아닙니다. 엔진
            오류와 저장 실패 회차는 이 목록에 나타나지 않을 수 있으니{" "}
            <Link className="underline" href="/history">
              측정 이력
            </Link>
            의 해당 회차에서 수집·오류·판별 상태를 함께 확인하세요.
          </p>
        </header>

        {responses.length === 0 ? (
          <section className="rounded-xl border border-[color:var(--findable-hairline,#23252a)] border-dashed p-6 text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
            이 질문으로 저장된 AI 답변이 아직 없습니다. 다음 측정을 완료한 뒤
            다시 확인해 주세요.
          </section>
        ) : (
          <section aria-label="엔진별 측정 원문" className="space-y-3">
            <p className="text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs">
              최근 응답 {responses.length}건 · 최신순
            </p>
            {responses.map((response, index) => (
              <details
                className="group overflow-hidden rounded-xl border border-[color:var(--findable-hairline,#23252a)] bg-[color:var(--findable-surface-1,#0f1011)]"
                key={response.id}
                open={index === 0}
              >
                <summary className="flex cursor-pointer list-none flex-wrap items-center gap-3 px-5 py-4 hover:bg-white/[0.025]">
                  <span className="font-medium text-[color:var(--findable-ink,#f7f8f8)] text-sm">
                    {response.engine.name}
                  </span>
                  <span className={responseVerdict(response).tone}>
                    {responseVerdict(response).label}
                  </span>
                  <time
                    className="ml-auto text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs"
                    dateTime={response.trackedAt.toISOString()}
                  >
                    {response.trackedAt.toLocaleString("ko-KR", {
                      timeZone: "Asia/Seoul",
                    })}
                  </time>
                </summary>
                <div className="border-[color:var(--findable-hairline,#23252a)] border-t px-5 py-5">
                  {response.rawResponse ? (
                    <div className="whitespace-pre-wrap break-words text-[color:var(--findable-ink-muted,#d0d6e0)] text-sm leading-7">
                      {response.rawResponse}
                    </div>
                  ) : (
                    <p className="text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
                      이 회차에는 저장된 답변 원문이 없습니다.
                    </p>
                  )}
                  {!response.errorMessage && response.mentionPosition ? (
                    <p className="mt-4 text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs">
                      과거 자동 추출 순위(브랜드 판별 미확인):{" "}
                      {response.mentionPosition}번째
                    </p>
                  ) : null}
                </div>
              </details>
            ))}
          </section>
        )}
      </main>
    </>
  );
}
