import { database } from "@repo/database";
import { ArrowLeftIcon } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireOrg } from "@/lib/db/scoped";
import { Header } from "../../components/header";
import { isPromptId } from "./prompt-id";

export const metadata: Metadata = {
  title: "질문별 AI 답변 · Findable",
};

export default async function PromptResponsesPage({
  params,
}: {
  params: Promise<{ promptId: string }>;
}) {
  const { promptId } = await params;
  if (!isPromptId(promptId)) {
    notFound();
  }
  const orgId = await requireOrg();
  // Prompt에는 orgId가 없으므로 브랜드 소유권을 반드시 관계 필터로 확인한다.
  const prompt = await database.prompt.findFirst({
    where: { id: promptId, brand: { organizationId: orgId } },
    select: {
      id: true,
      brandId: true,
      text: true,
      isAutoGenerated: true,
      brand: { select: { name: true, domain: true } },
    },
  });
  if (!prompt) {
    notFound();
  }
  const responses = await database.tracking.findMany({
    where: { promptId, brand: { organizationId: orgId } },
    orderBy: { trackedAt: "desc" },
    take: 70,
    select: {
      id: true,
      rawResponse: true,
      brandMentioned: true,
      mentionPosition: true,
      sentiment: true,
      errorMessage: true,
      trackedAt: true,
      engine: { select: { name: true } },
    },
  });

  return (
    <>
      <Header page="질문별 AI 답변" pages={["Findable", "추적 질문"]} />
      <main className="flex flex-1 flex-col gap-6 p-6 pt-2">
        <div className="flex flex-wrap items-center gap-4 text-sm">
          <Link
            className="inline-flex items-center gap-1 text-[color:var(--findable-ink-subtle,#8a8f98)] hover:text-[color:var(--findable-primary,#ff7a4d)]"
            href="/prompts"
          >
            <ArrowLeftIcon className="size-4" /> 추적 질문으로
          </Link>
          <Link
            className="text-[color:var(--findable-primary,#ff7a4d)] underline-offset-4 hover:underline"
            href={`/?brand=${prompt.brandId}#tracked-prompts`}
          >
            이 브랜드의 질문별 성적 보기 ↗
          </Link>
        </div>

        <header className="rounded-2xl border border-[color:var(--findable-hairline,#23252a)] bg-[color:var(--findable-surface-1,#0f1011)] p-6 sm:p-8">
          <p className="font-medium text-[color:var(--findable-primary,#ff7a4d)] text-xs uppercase tracking-[0.16em]">
            질문별 측정 원문
          </p>
          <h1 className="mt-3 max-w-3xl font-semibold text-2xl text-[color:var(--findable-ink,#f7f8f8)] leading-snug sm:text-3xl">
            {prompt.text}
          </h1>
          <p className="mt-3 text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
            {prompt.brand.name} · {prompt.brand.domain} · {prompt.isAutoGenerated ? "내가 고른 질문" : "기본 측정 질문"}
          </p>
          <p className="mt-4 max-w-3xl text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs leading-5">
            최근 최대 70개 응답의 전문입니다. 아래 언급 표시는 자동 판정이며, 실제로 등록한 브랜드를 말하는지 원문과 함께 확인하세요. 오류 응답은 등장률의 성공 분모에 포함하지 않습니다.
          </p>
        </header>

        {responses.length === 0 ? (
          <section className="rounded-xl border border-dashed border-[color:var(--findable-hairline,#23252a)] p-6 text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
            이 질문으로 저장된 AI 답변이 아직 없습니다. 다음 측정을 완료한 뒤 다시 확인해 주세요.
          </section>
        ) : (
          <section aria-label="AI 엔진별 측정 답변" className="space-y-3">
            <p className="text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs">
              최근 응답 {responses.length}건 · 최신순
            </p>
            {responses.map((response, index) => (
              <details
                className="group overflow-hidden rounded-xl border border-[color:var(--findable-hairline,#23252a)] bg-[color:var(--findable-surface-1,#0f1011)]"
                key={response.id}
                open={index === 0}
              >
                <summary className="flex cursor-pointer list-none flex-wrap items-center gap-3 px-5 py-4 hover:bg-white/[0.025]">
                  <span className="font-medium text-[color:var(--findable-ink,#f7f8f8)] text-sm">
                    {response.engine.name}
                  </span>
                  <span className={response.errorMessage
                    ? "text-amber-300 text-xs"
                    : response.brandMentioned
                      ? "text-emerald-300 text-xs"
                      : "text-[color:var(--findable-ink-subtle,#8a8f98)] text-xs"}
                  >
                    {response.errorMessage
                      ? "응답 수집 실패"
                      : response.brandMentioned
                        ? "자동 판정: 브랜드 언급"
                        : "자동 판정: 언급 없음"}
                  </span>
                  <time
                    className="ml-auto text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs"
                    dateTime={response.trackedAt.toISOString()}
                  >
                    {response.trackedAt.toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })}
                  </time>
                </summary>
                <div className="border-[color:var(--findable-hairline,#23252a)] border-t px-5 py-5">
                  {response.rawResponse ? (
                    <div className="whitespace-pre-wrap break-words text-[color:var(--findable-ink-muted,#d0d6e0)] text-sm leading-7">
                      {response.rawResponse}
                    </div>
                  ) : (
                    <p className="text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
                      이 회차에는 저장된 답변 원문이 없습니다.
                    </p>
                  )}
                  {!response.errorMessage && response.mentionPosition ? (
                    <p className="mt-4 text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs">
                      자동 추출된 언급 순위: {response.mentionPosition}번째
                    </p>
                  ) : null}
                </div>
              </details>
            ))}
          </section>
        )}
      </main>
    </>
  );
}
