-- Sales discovery DB: segments, company cards, facts with provenance, sales pipeline (2026-10-07).
-- Additive only: 1 new enum + 7 new tables + indexes. No existing table or column is altered or dropped.
-- Generated by `prisma migrate diff --from-schema <schema before> --to-schema prisma/schema.prisma --script`.
-- NOT applied to any database yet.
-- CreateEnum
CREATE TYPE "SalesLeadStatus" AS ENUM ('found', 'measured', 'reported', 'drafted', 'sent', 'replied', 'meeting', 'won', 'lost', 'opted_out');

-- CreateTable
CREATE TABLE "Segment" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "filter" JSONB NOT NULL,
    "autoRefresh" BOOLEAN NOT NULL DEFAULT true,
    "lastRefreshedAt" TIMESTAMP(3),
    "companyCount" INTEGER,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Segment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SegmentCompany" (
    "segmentId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SegmentCompany_pkey" PRIMARY KEY ("segmentId","companyId")
);

-- CreateTable
CREATE TABLE "Company" (
    "id" TEXT NOT NULL,
    "businessNumber" TEXT,
    "corpRegNo" TEXT,
    "dartCorpCode" TEXT,
    "legalName" TEXT NOT NULL,
    "normalizedName" TEXT NOT NULL,
    "domain" TEXT,
    "industry" "Industry",
    "industryCode" TEXT,
    "industryName" TEXT,
    "industrySource" TEXT,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "region" TEXT,
    "employeeCount" INTEGER,
    "employeeAsOf" TEXT,
    "employeeGrowth" DOUBLE PRECISION,
    "foundedYear" INTEGER,
    "sources" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "matchConfidence" TEXT NOT NULL DEFAULT 'name_only',
    "lastMeasuredScore" INTEGER,
    "lastMeasuredAt" TIMESTAMP(3),
    "lastEnrichedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Company_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CompanyFact" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "field" TEXT NOT NULL,
    "value" JSONB NOT NULL,
    "source" TEXT NOT NULL,
    "sourceRef" TEXT,
    "asOf" TEXT NOT NULL DEFAULT '',
    "fetchedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CompanyFact_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CompanyContact" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "personalName" BOOLEAN NOT NULL DEFAULT false,
    "confidence" TEXT,
    "label" TEXT,
    "sourceUrl" TEXT NOT NULL,
    "fetchedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CompanyContact_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SalesLead" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "contactId" TEXT,
    "segmentId" TEXT,
    "status" "SalesLeadStatus" NOT NULL DEFAULT 'found',
    "statusChangedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reportUrl" TEXT,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SalesLead_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactBasis" (
    "id" TEXT NOT NULL,
    "leadId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "detail" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "evidenceUrl" TEXT,
    "recordedBy" TEXT NOT NULL,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ContactBasis_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "SegmentCompany_companyId_idx" ON "SegmentCompany"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "Company_businessNumber_key" ON "Company"("businessNumber");

-- CreateIndex
CREATE INDEX "Company_normalizedName_region_idx" ON "Company"("normalizedName", "region");

-- CreateIndex
CREATE INDEX "Company_industry_idx" ON "Company"("industry");

-- CreateIndex
CREATE INDEX "Company_region_idx" ON "Company"("region");

-- CreateIndex
CREATE INDEX "Company_domain_idx" ON "Company"("domain");

-- CreateIndex
CREATE INDEX "Company_employeeCount_idx" ON "Company"("employeeCount");

-- CreateIndex
CREATE INDEX "Company_tags_idx" ON "Company" USING GIN ("tags");

-- CreateIndex
CREATE INDEX "CompanyFact_companyId_field_fetchedAt_idx" ON "CompanyFact"("companyId", "field", "fetchedAt");

-- CreateIndex
CREATE UNIQUE INDEX "CompanyFact_companyId_field_source_asOf_key" ON "CompanyFact"("companyId", "field", "source", "asOf");

-- CreateIndex
CREATE UNIQUE INDEX "CompanyContact_companyId_email_key" ON "CompanyContact"("companyId", "email");

-- CreateIndex
CREATE INDEX "SalesLead_status_idx" ON "SalesLead"("status");

-- CreateIndex
CREATE INDEX "SalesLead_contactId_idx" ON "SalesLead"("contactId");

-- CreateIndex
CREATE INDEX "SalesLead_segmentId_idx" ON "SalesLead"("segmentId");

-- CreateIndex
CREATE UNIQUE INDEX "SalesLead_companyId_key" ON "SalesLead"("companyId");

-- CreateIndex
CREATE INDEX "ContactBasis_leadId_recordedAt_idx" ON "ContactBasis"("leadId", "recordedAt");
