import { RUNNER_PROMPT_LIMIT } from "@repo/audit/runner";
import { planCapabilities } from "@repo/auth/plan";
import { getCurrentPlan } from "@repo/auth/plan-server";
import { database } from "@repo/database";
import type { Metadata } from "next";
import Link from "next/link";
import { deletePromptAction } from "@/app/actions/brand/delete-prompt";
import { editPromptAction } from "@/app/actions/brand/edit-prompt";
import { requireOrg, scopedBrands } from "@/lib/db/scoped";
import { Header } from "../components/header";
import { PromptWizard } from "../features/brand/prompt-wizard";
import { PromptList } from "./prompt-list";

export const metadata: Metadata = {
  title: "추적 질문 · Findable",
  description: "AI에게 무엇을 물어볼지 고르면, 그 질문으로 측정해요.",
};

/**
 * 「추적 질문」 탭 (세션N-41).
 *
 * 🔴 **왜 최상위 탭인가** — 경쟁사 4곳(Profound·Otterly·Peec·Scrunch)이 **전부**
 *   `Prompts` 를 최상위 탭으로 갖는다(실측: 내비 OCR). GEO 는 *"어떤 질문으로 재나"* 가
 *   결과를 전부 결정하기 때문이다. 우리는 그 자산(`PromptWizard`)을 **이미 갖고 있었는데
 *   `/brand` 페이지 안에 묻혀 있었다** — 가장 중요한 입력이 가장 안 보이는 곳에 있었다.
 *
 * 🔴 **이 화면이 새로 주는 것 = 목록과 삭제.** 마법사는 **추가만** 했다(감사 실측:
 *   저장된 질문을 보여주는 화면 0곳 · 고객용 삭제 경로 0곳). 그래서 상한에 걸리면
 *   "상한 도달"만 듣고 **무엇을 지울지 몰라 막다른 길**이었다.
 *
 * ⚠️ 상한 규칙을 **다시 세지 않는다** — `planCapabilities().promptLimit` +
 *   `count({isAutoGenerated:true})` 는 `suggest-prompts.ts:138` 이 쓰는 것과 **같은 축**이다
 *   (같은 값을 세는 코드를 복제하면 화면과 저장이 갈린다 — 「7/6」·「117%」 사고).
 */
const PromptsPage = async () => {
  await requireOrg();
  const brands = await scopedBrands();
  const plan = await getCurrentPlan();
  const promptLimit = planCapabilities(plan).promptLimit;

  // 🔴 `isAutoGenerated: true` 만 = **고객이 고른 추적대상**.
  //   `false`(시스템 기본질문)는 폴백 측정의 원장이라 고객 화면에 섞지 않는다
  //   (섞으면 지울 수 없는 항목이 목록에 끼고 상한 계산도 어긋난다).
  const brandIds = brands.map((brand) => brand.id);
  const prompts =
    brandIds.length > 0
      ? await database.prompt.findMany({
          where: { brandId: { in: brandIds }, isAutoGenerated: true },
          orderBy: { createdAt: "desc" },
          select: {
            id: true,
            brandId: true,
            text: true,
            language: true,
            category: true,
            // 이 질문으로 실제 몇 번 측정됐는지 — 삭제 시 사라지는 양을 미리 알린다.
            _count: { select: { trackings: true } },
          },
        })
      : [];

  return (
    <>
      <Header page="추적 질문" pages={["Findable"]} />
      <div className="flex flex-1 flex-col gap-6 p-6 pt-2">
        <section className="flex flex-col gap-2">
          <h1 className="font-semibold text-2xl text-[color:var(--findable-ink,#f7f8f8)]">
            추적 질문
          </h1>
          <p className="max-w-2xl text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
            AI에게 무엇을 물어볼지가 결과를 정해요. 여기서 고른 질문으로
            ChatGPT·Perplexity·네이버 등에 물어보고, 우리 브랜드가 답변에
            나오는지 셉니다.
          </p>
        </section>

        {brands.length === 0 ? (
          /* 브랜드가 없으면 질문을 만들 대상이 없다 — 빈 목록을 보여주는 대신
             해야 할 일 하나만 준다(빈 화면에 영업·설명을 쌓지 않는다). */
          <section className="flex flex-col items-start gap-3 rounded-lg border border-[color:var(--findable-hairline,#23252a)] bg-[color:var(--findable-surface-1,#0f1011)] p-6">
            <p className="text-[color:var(--findable-ink-muted,#d0d6e0)] text-sm">
              먼저 브랜드를 등록하면 그 브랜드에 맞는 질문을 제안해 드려요.
            </p>
            <Link
              className="findable-btn-primary inline-flex items-center rounded-md px-4 py-2 font-medium text-sm"
              href="/brand"
            >
              브랜드 등록하기
            </Link>
          </section>
        ) : (
          brands.map((brand) => {
            const mine = prompts.filter(
              (prompt) => prompt.brandId === brand.id
            );
            return (
              <section className="flex flex-col gap-3" key={brand.id}>
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <h2 className="font-medium text-[color:var(--findable-ink,#f7f8f8)]">
                    {brand.name}
                    <span className="ml-2 text-[color:var(--findable-ink-subtle,#8a8f98)] text-sm">
                      {brand.domain}
                    </span>
                  </h2>
                  {/* 상한을 **분모와 함께** 밝힌다(모집단 명시 규율 · N-40).
                      `Infinity` 플랜은 숫자를 쓰지 않는다(「∞개 중」은 읽히지 않는다). */}
                  <span className="text-[color:var(--findable-ink-tertiary,#7e8289)] text-sm tabular-nums">
                    {Number.isFinite(promptLimit)
                      ? `질문 ${mine.length} / ${promptLimit}개`
                      : `질문 ${mine.length}개`}
                  </span>
                </div>
                {/* 🔴 2026-08-22 — 저장 상한(요금제별 최대 150개)과 러너가 한 번에
                    측정하는 상한(8개, 원가 방어선)이 다르다. 화면이 저장 개수만
                    안내하면 "돈 내고 저장했는데 왜 다 안 재나"로 오해할 수 있어,
                    8개 넘게 저장했을 때만 순환 측정 사실을 정직하게 알린다
                    (화면은 의도를, 코드는 사실을 원칙). */}
                {mine.length > RUNNER_PROMPT_LIMIT && (
                  <p className="text-[color:var(--findable-ink-tertiary,#7e8289)] text-xs">
                    측정마다 {RUNNER_PROMPT_LIMIT}개씩 돌아가며 측정돼요 ·
                    저장한 질문이 많을수록 한 바퀴 도는 데 며칠 걸릴 수 있어요
                  </p>
                )}

                <PromptList
                  // 🔴 서버액션을 **주입**한다 — `PromptList` 가 직접 import 하면
                  //   `node:*` 가 브라우저 번들로 끌려와 Storybook 이 통째로 죽는다
                  //   (N-41 실측 · N-37 과 같은 함정).
                  onDelete={deletePromptAction}
                  onEdit={editPromptAction}
                  prompts={mine.map((prompt) => ({
                    id: prompt.id,
                    text: prompt.text,
                    language: prompt.language,
                    category: prompt.category,
                    measuredCount: prompt._count.trackings,
                  }))}
                />

                <div className="flex flex-wrap items-center gap-2">
                  <PromptWizard brandId={brand.id} />
                  {/* 상한에 닿았으면 그 자리에서 길을 준다 — 마법사만 두면
                      누른 뒤에야 "상한 도달" 토스트를 만난다. */}
                  {Number.isFinite(promptLimit) &&
                  mine.length >= promptLimit ? (
                    <Link
                      className="text-[color:var(--findable-primary,#ff7a4d)] text-sm"
                      href="/billing"
                    >
                      상한에 닿았어요 · 요금제 보기
                    </Link>
                  ) : null}
                </div>
              </section>
            );
          })
        )}
      </div>
    </>
  );
};

export default PromptsPage;
