// 네이버 AI 브리핑 on-demand 러너 (D-2026-07-22)
//
// 트리거: 사용자가 무료 Audit 결과 페이지에서 "네이버 AI 브리핑 측정" 클릭
// 실행: AuditJob의 기존 result에 naver-briefing 엔진 응답 1개를 추가 측정
// 출력: AuditJob.result JSON에 engineResponse append + metrics 재계산
//       + briefingStatus="completed"
//
// after()로 백그라운드 실행. Browserbase 클라우드 크롬 사용 (느림 + 무료 티어 1동시)
// 이라 본류 7 엔진과 분리해 on-demand로만 호출한다.
//
// crew-runner.ts 구조 미러. 단, crewResult는 별도 컬럼이라 단순 write지만
// briefingStatus·engineResponses는 result JSON을 공유하므로 read-modify-write
// (최신 result 재조회 후 병합)로 다른 필드 덮어쓰기를 막는다.

import { resolveBrandIdentity } from "@repo/ai/lib/brand-identity";
import type { CitedSource, EngineResponse } from "@repo/ai/lib/engines";
import { aggregateAudit, queryAllEngines } from "@repo/ai/lib/engines";
import { BRIEFING_FAIL_PREFIX } from "@repo/ai/lib/engines/naver-briefing-adapter";
import { verifyMentions } from "@repo/ai/lib/mention-verdict";
import { database } from "@repo/database";
import { parseError } from "@repo/observability/error";
import { log } from "@repo/observability/log";
import { keys } from "./keys";
import { persistAuditTracking } from "./tracking";

interface BriefingRunInput {
  jobId: string;
}

/**
 * **재시도해도 안 풀리는 실패인가** — 후보 질의 루프를 즉시 끊을지 판정한다.
 *
 * 🔴 세션N-39: 전에는 「브리핑 미노출」과 「크레딧 소진」을 구분 못 해, 크레딧이
 *   마른 상태에서도 후보 질의를 끝까지 돌며 **없는 크레딧을 3번 더 긁었다.**
 *   402(크레딧)·401(키)는 **사람이 조치해야** 풀리므로 재시도가 무의미하다.
 *
 * ⚠️ 429(속도제한)·5xx 는 **여기 넣지 않는다** — 잠시 뒤 재시도하면 풀리는데
 *   치명으로 분류하면 일시 장애에 측정을 통째로 포기하게 된다.
 *   (근거: Firecrawl 공식 문서 — 재시도 가능은 408·429·5xx)
 */
function isUnrecoverableBriefingFailure(
  errorMessage: string | null | undefined
): boolean {
  if (!errorMessage) {
    return false;
  }
  return (
    errorMessage.startsWith(BRIEFING_FAIL_PREFIX.credits) ||
    errorMessage.startsWith(BRIEFING_FAIL_PREFIX.auth)
  );
}

// runner.ts의 result 형태 (JSON deserialize 후). EngineId 브랜딩은 소실됨.
interface StoredEngineResponse {
  brandMentioned: boolean;
  durationMs: number;
  engineId: string;
  errorMessage: string | null;
  excerpt: string;
  isStub: boolean;
  /** 순위의 분모(세션N-10). 도입 전 저장분은 undefined → 복원 시 null. */
  mentionListSize?: number | null;
  mentionPosition: number | null;
  sentiment: "positive" | "neutral" | "negative" | null;
  sov: number | null;
  /** crew-runner가 심층 출처 분석에 쓰는 측정 원본. 구 리포트에는 없다. */
  citedSources?: CitedSource[];
}

interface StoredResult {
  brandName: string;
  /** 브리핑 측정에 채택된 검색 질의 — 카드가 답변의 맥락을 설명하는 데 쓴다. */
  briefingPrompt?: string;
  briefingStatus?: "not_requested" | "processing" | "completed" | "failed";
  domain: string;
  engineResponses: StoredEngineResponse[];
  metrics: ReturnType<typeof aggregateAudit>;
  measurementContext?: {
    identityGrounded: boolean;
    officialSiteIdentity: {
      description?: string | null;
      finalUrl?: string;
      h1?: string | null;
      siteName?: string | null;
      title?: string | null;
    } | null;
  };
  promptsCount: number;
  topRecommendations: string[];
}

function toStoredEngineResponse(r: EngineResponse): StoredEngineResponse {
  return {
    engineId: r.engineId,
    brandMentioned: r.brandMentioned,
    mentionPosition: r.mentionPosition,
    mentionListSize: r.mentionListSize,
    sentiment: r.sentiment,
    sov: r.shareOfVoice,
    durationMs: r.durationMs,
    isStub: r.isStub,
    errorMessage: r.errorMessage,
    citedSources: r.citedSources,
    // runner.ts의 excerpt 한도(4000자)와 정합. 브리핑 텍스트는 어댑터가 이미 4000자 캡.
    excerpt: r.rawResponse.slice(0, 4000),
  };
}

/** `persistBriefingTracking` 입력 — 러너 본문의 복잡도를 낮추려 분리했다. */
interface BriefingTrackingInput {
  adoptedPrompt: string;
  brandId: string | null;
  briefing: StoredEngineResponse | undefined;
  completedAt: Date | null;
  jobId: string;
  language: "ko" | "en";
  organizationId: string | null;
  responses: EngineResponse[];
}

/**
 * 브리핑 결과를 **시계열(Tracking)** 로 적재한다.
 *
 * 🔴 **이 러너는 원래 Tracking 에 한 줄도 안 쌓았다**(2026-08-17 세션N-38 발견).
 *   `persistAuditTracking` 호출처가 `runner.ts` 한 곳뿐이라 브리핑 결과는
 *   `AuditJob.result` JSON 에만 남았다.
 *   [실측] `Tracking` 엔진별 집계에 `naver-briefing` 행 **0개** — 11번 돌았는데도 비어 있었다.
 *   = N-36 과 **같은 유형의 조용한 유실**(측정 성공·화면 정상·시계열만 증발).
 *   브리핑을 파는 이유가 「네이버 AI 답변에서 우리가 어떻게 변하는가」이므로
 *   추세에 안 잡히면 이 엔진은 **일회성 스냅샷 이상이 될 수 없다.**
 *
 * ⚠️ `promptText` 는 본류 프롬프트가 아니라 **브리핑이 실제로 던진 질의**(`adoptedPrompt`)다.
 *   브리핑은 정보형("{브랜드} 효과·후기·장단점")에만 뜨므로 축이 다르다.
 *
 * 🔴🔴 `promptIsAutoGenerated: false` 가 **필수**다. `tracking.ts` 는 원래
 *   `isAutoGenerated: true` 를 하드코딩했는데, 그대로였으면 브리핑 질의가
 *   마법사의 요금제 상한을 잠식해 **무료 고객(상한 5)이 측정 한 번에 할당량을 잃고**
 *   「상한 도달, 요금제를 올리세요」라는 **거짓 안내**가 나갔을 것이다(N-36 이 막은 사고).
 */
async function persistBriefingTracking(
  input: BriefingTrackingInput
): Promise<void> {
  const {
    jobId,
    organizationId,
    brandId,
    briefing,
    completedAt,
    responses,
    adoptedPrompt,
    language,
  } = input;
  const dualWriteEnabled = keys().AUDIT_DUAL_WRITE_ENABLED;
  const usable = Boolean(
    completedAt && briefing && !(briefing.isStub || briefing.errorMessage)
  );

  if (
    dualWriteEnabled &&
    organizationId &&
    brandId &&
    completedAt &&
    usable
  ) {
    await persistAuditTracking({
      organizationId,
      brandId,
      // 본 측정과 정확히 같은 run key를 써야 한다. 새 시각을 만들면 이 한 줄이
      // 최신 전체 측정으로 오인되어 SoV·추세가 100%가 되는 회귀가 발생한다.
      completedAt,
      // 🔴 시스템 질의다 — 고객 할당량 축이 아니다(위 주석).
      promptIsAutoGenerated: false,
      tagged: responses.map((r) => ({
        ...r,
        promptText: adoptedPrompt,
        promptLang: language,
      })),
    });
    return;
  }

  // 🔴 건너뛸 때는 **이유를 남긴다** — N-36 의 교훈. 조용히 지나가면 다음 사람도
  //   "왜 시계열이 비어 있는지"를 3주 동안 못 찾는다.
  log.warn("audit.briefing.tracking_skipped", {
    jobId,
    reason: dualWriteEnabled
      ? "missing_org_or_brand_or_unusable"
      : "flag_disabled",
    flagEnabled: dualWriteEnabled,
    hasOrganizationId: Boolean(organizationId),
    hasBrandId: Boolean(brandId),
    hasCompletedAt: Boolean(completedAt),
    isStub: briefing?.isStub ?? true,
    hasError: Boolean(briefing?.errorMessage),
  });
}

/**
 * AuditJob의 기존 result에 네이버 AI 브리핑 측정을 추가하고 metrics 재계산 → DB 업데이트.
 */
export async function runBriefingForAuditJob(
  input: BriefingRunInput
): Promise<void> {
  const { jobId } = input;

  try {
    // processing 상태로 전환 — result JSON은 공유하므로 최신 재조회 후 병합.
    const jobBefore = await database.auditJob.findUnique({
      where: { id: jobId },
      // 🔴 세션N-38: `organizationId`·`brandId` 를 함께 읽는다 — Tracking 적재용(아래 §시계열).
      select: {
        result: true,
        domain: true,
        language: true,
        industry: true,
        organizationId: true,
        brandId: true,
        completedAt: true,
      },
    });
    if (!jobBefore?.result) {
      throw new Error(
        "AuditJob.result가 비어있습니다. 빠른 모드 Audit이 먼저 완료되어야 합니다."
      );
    }
    const resultProcessing = jobBefore.result as unknown as StoredResult;
    await database.auditJob.update({
      where: { id: jobId },
      data: {
        result: { ...resultProcessing, briefingStatus: "processing" } as never,
      },
    });

    // 네이버 AI 브리핑은 "정보/정답형" 질의에서만 노출된다(2026-07-23 실측).
    //   ✅ 노출: "{브랜드} 효과" · "{브랜드} 후기" · "{브랜드} 장단점"
    //   ❌ 미노출: "{브랜드} 추천/어때" · "{카테고리} 추천" · 경쟁사 추천형
    // 단일 질의는 미노출 위험이 있어 노출률 높은 순으로 여러 유형을 순차 시도하고
    // 브리핑이 실제로 뜬(errorMessage 없고 응답 존재) 첫 결과를 채택한다.
    // (Browserbase 무료 동시성 1이라 병렬 대신 순차 — 뜨면 즉시 중단해 호출 절약.)
    const language = jobBefore.language === "en" ? "en" : "ko";
    const brand = resultProcessing.brandName;
    // 언급 판정용 브랜드 변형 복원(2026-07-30 결함감사 §20): 기존엔 [brand] 하나만
    // 넘겨 원 측정 때의 한/영 변형이 소실됐고("엔비디아"만 남고 "NVIDIA" 없음),
    // 브리핑이 영문 표기로 답하면 명백한 언급도 false로 판정됐다.
    // 본 러너(runner.ts)와 동일한 해석 체인으로 변형을 복원한다.
    const identity = await resolveBrandIdentity(resultProcessing.domain, brand);
    const brandVariants = [...new Set([brand, ...identity.brandVariants])];
    const candidatePrompts =
      language === "en"
        ? [`${brand} review`, `${brand} pros and cons`, `Is ${brand} good`]
        : [`${brand} 효과`, `${brand} 후기`, `${brand} 장단점`];

    // 채택된 질의를 결과에 기록한다(전수감사 2026-08-02 §A-5).
    //   "SK하이닉스 후기" 답변이 왜 나왔는지 화면이 설명 못 해 사용자가
    //   "너가 이상한 걸 물어본 건가?"라고 물었다 — 질의를 보여주면 해소된다.
    let adoptedPrompt = candidatePrompts[0] as string;
    let briefingResponses = await queryAllEngines(
      {
        prompt: candidatePrompts[0],
        language,
        brandName: brand,
        brandVariants,
      },
      ["naver-briefing"] as never
    );

    // 첫 질의가 미노출이면 다음 후보로 재시도 (하나라도 뜨면 채택).
    for (let i = 1; i < candidatePrompts.length; i++) {
      const first = briefingResponses[0];
      const shown =
        first &&
        !first.isStub &&
        !first.errorMessage &&
        first.rawResponse.length > 0;
      if (shown) {
        break;
      }
      // 🔴 재시도해도 안 풀리는 실패면 **즉시 멈춘다**(세션N-39).
      //   전에는 「미노출」과 「크레딧 소진」을 구분 못 해, 크레딧이 마른 상태에서도
      //   후보 질의를 끝까지 돌며 **없는 크레딧을 3번 더 긁었다**.
      if (isUnrecoverableBriefingFailure(first?.errorMessage)) {
        log.error("audit.briefing.firecrawl_blocked", {
          jobId,
          reason: first.errorMessage?.slice(0, 200),
          attemptedPrompts: i,
          hint: "Firecrawl 크레딧 충전 또는 FIRECRAWL_API_KEY 재설정이 필요합니다.",
        });
        break;
      }
      adoptedPrompt = candidatePrompts[i] as string;
      briefingResponses = await queryAllEngines(
        {
          prompt: candidatePrompts[i],
          language,
          brandName: brand,
          brandVariants,
        },
        ["naver-briefing"] as never
      );
    }

    // 브리핑도 본류 측정과 같은 언급 판정을 통과한다. 이 경로만 문자열
    // 매칭을 그대로 쓰면 동명의 노래·학원·작품이 대시보드에 다시 확정 언급으로 쌓인다.
    briefingResponses = await verifyMentions(briefingResponses, {
      brandName: brand,
      brandDomain: resultProcessing.domain,
      industry: jobBefore.industry ?? undefined,
      officialSite:
        resultProcessing.measurementContext?.officialSiteIdentity ?? null,
    });

    // read-modify-write: crew 자동 실행 등으로 result가 바뀌었을 수 있어 최신 재조회.
    const jobAfter = await database.auditJob.findUnique({
      where: { id: jobId },
      select: { result: true },
    });
    if (!jobAfter?.result) {
      throw new Error("AuditJob.result가 사라졌습니다.");
    }
    const latest = jobAfter.result as unknown as StoredResult;

    // naver-briefing 기존 응답 제거 후 새 응답 append (중복 방지 / 재측정 반영).
    const withoutBriefing = latest.engineResponses.filter(
      (r) => r.engineId !== "naver-briefing"
    );
    const newStored = briefingResponses.map(toStoredEngineResponse);
    const mergedStored = [...withoutBriefing, ...newStored];

    // 브리핑은 효과·후기·장단점이라는 별도 질문 축이다. 응답 카드는 붙이되,
    // 본류 추천/비교 질문으로 확정한 등장률·점수 분모는 그대로 보존한다.
    const metrics = latest.metrics;

    const mergedResult: StoredResult = {
      ...latest,
      briefingStatus: "completed",
      // 화면이 "무슨 질문을 던졌는지" 보여줄 수 있게 채택 질의를 함께 저장.
      briefingPrompt: adoptedPrompt,
      engineResponses: mergedStored,
      metrics,
    };

    await database.auditJob.update({
      where: { id: jobId },
      data: { result: mergedResult as never },
    });

    const briefing = newStored[0];
    log.info("audit.briefing.completed", {
      jobId,
      isStub: briefing?.isStub ?? true,
      brandMentioned: briefing?.brandMentioned ?? false,
      errorMessage: briefing?.errorMessage ?? null,
    });

    await persistBriefingTracking({
      jobId,
      organizationId: jobBefore.organizationId,
      brandId: jobBefore.brandId,
      completedAt: jobBefore.completedAt,
      briefing,
      responses: briefingResponses,
      adoptedPrompt,
      language,
    });
  } catch (error) {
    log.error("audit.briefing.failed", {
      jobId,
      error: parseError(error),
    });
    // 실패 상태 병합 — 최신 result 재조회 후 briefingStatus만 갱신.
    try {
      const jobFail = await database.auditJob.findUnique({
        where: { id: jobId },
        select: { result: true },
      });
      if (jobFail?.result) {
        const latest = jobFail.result as unknown as StoredResult;
        await database.auditJob.update({
          where: { id: jobId },
          data: { result: { ...latest, briefingStatus: "failed" } as never },
        });
      }
    } catch (mergeErr) {
      log.error("audit.briefing.failed_status_merge_failed", {
        jobId,
        error: parseError(mergeErr),
      });
    }
  }
}
