import { randomUUID } from "node:crypto";
import { database } from "@repo/database";
import { log } from "@repo/observability/log";
import { persistAuditTracking, type TaggedEngineResponse } from "./tracking";

type ReconcileDatabase = Pick<typeof database, "$executeRawUnsafe">;

/** A separate marker prevents briefing replay from changing core score state. */
export async function claimBriefingTracking(
  db: ReconcileDatabase,
  jobId: string,
  startedAt = new Date(),
  token: string = randomUUID()
): Promise<string | null> {
  const staleBefore = new Date(startedAt.getTime() - 10 * 60 * 1000);
  const claimed = await db.$executeRawUnsafe(
    `UPDATE "AuditJob"
     SET "postprocessing" = jsonb_set(jsonb_set(jsonb_set(
       COALESCE("postprocessing", '{}'::jsonb),
       '{briefingTracking}', '"reconciling"', true),
       '{briefingTrackingReconcileStartedAt}', to_jsonb($2::text), true),
       '{briefingTrackingReconcileToken}', to_jsonb($3::text), true)
     WHERE "id" = $1 AND "status" = 'completed'
       AND "result"->>'briefingStatus' = 'completed'
       AND (
         "postprocessing"->>'briefingTracking' IN ('pending', 'unknown')
         OR ("postprocessing"->>'briefingTracking' = 'reconciling'
           AND ("postprocessing"->>'briefingTrackingReconcileStartedAt')::timestamptz < $4::timestamptz)
       )`,
    jobId,
    startedAt.toISOString(),
    token,
    staleBefore.toISOString()
  );
  return claimed === 1 ? token : null;
}

export async function finalizeBriefingTracking(
  db: ReconcileDatabase,
  jobId: string,
  token: string,
  status: "completed" | "unknown"
): Promise<number> {
  return db.$executeRawUnsafe(
    `UPDATE "AuditJob"
     SET "postprocessing" = jsonb_set(jsonb_set(jsonb_set(
       COALESCE("postprocessing", '{}'::jsonb),
       '{briefingTracking}', to_jsonb($3::text), true),
       '{briefingTrackingReconcileStartedAt}', 'null', true),
       '{briefingTrackingReconcileToken}', 'null', true)
     WHERE "id" = $1 AND "status" = 'completed'
       AND "postprocessing"->>'briefingTracking' = 'reconciling'
       AND "postprocessing"->>'briefingTrackingReconcileToken' = $2`,
    jobId,
    token,
    status
  );
}

/** Replay only a captured on-demand briefing snapshot; never re-run the provider. */
export async function reconcileBriefingTracking(
  jobId: string
): Promise<"completed" | "failed" | "skipped"> {
  const job = await database.auditJob.findUnique({
    where: { id: jobId },
    select: {
      status: true,
      organizationId: true,
      brandId: true,
      completedAt: true,
      result: true,
      postprocessing: true,
    },
  });
  if (!job || job.status !== "completed" || !job.organizationId ||
    !job.brandId || !job.completedAt || !job.result) return "skipped";

  const marker = job.postprocessing && typeof job.postprocessing === "object" &&
    !Array.isArray(job.postprocessing)
      ? (job.postprocessing as { briefingTracking?: unknown }).briefingTracking
      : undefined;
  if (marker !== "pending" && marker !== "unknown" && marker !== "reconciling") return "skipped";

  const token = await claimBriefingTracking(database, jobId);
  if (!token) return "skipped";
  const result = job.result as {
    briefingStatus?: unknown;
    briefingPrompt?: unknown;
    engineResponses?: Array<Record<string, unknown>>;
  };
  const tagged: TaggedEngineResponse[] = (result.engineResponses ?? [])
    .filter((row) => row.engineId === "naver-briefing" &&
      row.trackingInputCaptured === true && row.promptIndex === 0 &&
      typeof row.promptText === "string" && row.promptText === result.briefingPrompt &&
      (row.promptLang === "ko" || row.promptLang === "en") &&
      typeof row.rawResponse === "string" && row.rawResponse.length > 0 &&
      row.isStub === false && !row.errorMessage)
    .map((row) => ({
      ...(row as unknown as TaggedEngineResponse),
      citedSources: Array.isArray(row.citedSources) ? row.citedSources : [],
      shareOfVoice: typeof row.shareOfVoice === "number" ? row.shareOfVoice : null,
      usage: row.usage && typeof row.usage === "object"
        ? row.usage as TaggedEngineResponse["usage"] : undefined,
    }));

  if (result.briefingStatus !== "completed" || tagged.length !== 1) {
    log.warn("audit.briefing.tracking_unreplayable_snapshot", { jobId });
    await finalizeBriefingTracking(database, jobId, token, "unknown");
    return "skipped";
  }

  const status = await persistAuditTracking({
    auditJobId: jobId,
    organizationId: job.organizationId,
    brandId: job.brandId,
    completedAt: job.completedAt,
    trackingAxis: "briefing",
    promptIsAutoGenerated: false,
    tagged,
  });
  const updated = await finalizeBriefingTracking(
    database, jobId, token, status === "completed" ? "completed" : "unknown"
  );
  if (updated !== 1) log.warn("audit.briefing.tracking_lost_claim", { jobId });
  return status;
}
