"use server";

import { database } from "@repo/database";
import { parseError } from "@repo/observability/error";
import { log } from "@repo/observability/log";
import { requireOrg, scopedBrandById } from "@/lib/db/scoped";

/**
 * 추적 질문 삭제 (세션N-41 · 「질문」 탭).
 *
 * 🔴 **왜 필요했나**: 마법사(`suggest-prompts.ts`)는 질문을 **추가만** 할 수 있었고
 *   고객이 **자기가 무엇을 추적 중인지 볼 수도, 지울 수도 없었다**(감사 실측: 고객용
 *   삭제 경로 0곳 · `admin/measure.ts:191` 의 브랜드 전체 `deleteMany` 뿐).
 *   그래서 플랜 상한(free 5/starter 30/growth 150)에 걸리면 *"상한 도달"* 이라는 말만
 *   듣고 **무엇을 지워야 할지 몰라 막다른 길**이었다.
 *   경쟁사 4곳은 전부 `Prompts` 를 최상위 탭으로 갖고 목록·편집을 준다.
 *
 * 🔒 보안(`suggest-prompts.ts`·`start-tracking.ts` 와 **같은 불변식**):
 *   - orgId 는 세션에서 `requireOrg()` 로 서버 재도출(클라이언트 입력 신뢰 안 함)
 *   - 질문의 소유 브랜드를 `scopedBrandById` 로 검증 → 남의 org 질문 삭제 차단
 *   - 삭제 대상은 **id 로만** 지정(텍스트 매칭 금지 — 동명 질문 오삭제 방지)
 *
 * 🔴 **축을 지킨다** — `isAutoGenerated: true`(고객이 고른 추적대상)만 지운다.
 *   `false` 는 **시스템 기본질문**(폴백 측정이 쓰는 원장)이라 지우면 측정이 깨진다.
 *   📕 N-36 사고의 반대편: 그때는 폴백을 `true` 로 심어 고객 할당량을 깎았다.
 *   두 방향 모두 **축이 섞이면** 터진다.
 *
 * ⚠️ **시계열이 함께 사라진다.** `Tracking.promptId` 는 `onDelete: Cascade`
 *   (`schema.prisma:127`)라 이 질문으로 측정한 **과거 행이 전부 삭제된다**.
 *   → 호출부(UI)가 **그 사실을 밝히고 확인**받아야 한다. 조용히 지우면 데이터 유실이다.
 *   그래서 이 액션은 삭제한 Tracking 행 수를 **반환**한다(화면이 사후 보고할 수 있게).
 */

export type DeletePromptResult =
  | { ok: true; deletedTrackings: number }
  | { error: string };

export const deletePromptAction = async (input: {
  promptId: string;
}): Promise<DeletePromptResult> => {
  try {
    await requireOrg();
  } catch {
    return { error: "로그인 후 조직을 선택해 주세요." };
  }

  const prompt = await database.prompt.findUnique({
    where: { id: input.promptId },
    select: { id: true, brandId: true, isAutoGenerated: true },
  });
  if (!prompt) {
    return { error: "질문을 찾을 수 없어요." };
  }

  // 🔒 이 질문의 브랜드가 **현재 org 소속**인지 검증(남의 org 차단).
  const brand = await scopedBrandById(prompt.brandId);
  if (!brand) {
    return { error: "질문을 찾을 수 없어요." };
  }

  // 🔴 시스템 기본질문은 고객이 지울 수 없다(폴백 측정의 원장).
  if (!prompt.isAutoGenerated) {
    return {
      error: "기본 질문은 지울 수 없어요. 직접 추가한 질문만 삭제할 수 있어요.",
    };
  }

  try {
    // 몇 개의 측정 기록이 함께 사라지는지 **먼저 센다**(삭제 후에는 셀 수 없다).
    const deletedTrackings = await database.tracking.count({
      where: { promptId: prompt.id },
    });
    await database.prompt.delete({ where: { id: prompt.id } });

    log.info("brand.prompt.deleted", {
      brandId: brand.id,
      promptId: prompt.id,
      deletedTrackings,
    });
    return { ok: true, deletedTrackings };
  } catch (error) {
    log.error("brand.prompt.delete_failed", {
      brandId: brand.id,
      promptId: prompt.id,
      error: parseError(error),
    });
    return { error: "삭제하지 못했어요. 잠시 후 다시 시도해 주세요." };
  }
};
