"use server";

import { database } from "@repo/database";
import { parseError } from "@repo/observability/error";
import { log } from "@repo/observability/log";
import { requireOrg, scopedBrandById } from "@/lib/db/scoped";

/**
 * 추적 질문 텍스트 수정 (RICE#8 · 세션N-52).
 *
 * 🔴 **왜 필요했나**: 지금은 텍스트를 바꾸려면 삭제→재생성뿐이다. `Tracking.promptId`
 *   가 `onDelete: Cascade`(schema.prisma:127)라 삭제 순간 **그 질문의 과거 시계열이
 *   전부 사라진다**(`delete-prompt.ts` 참고). 오타 하나 고치려다 측정 이력을 잃는
 *   구조 — 이 액션은 `id`(=promptId)를 유지한 채 `text`만 바꿔 시계열을 보존한다.
 *
 * 🔒 보안(`delete-prompt.ts`·`suggest-prompts.ts`와 같은 불변식):
 *   - orgId는 세션에서 `requireOrg()`로 서버 재도출.
 *   - 질문의 소유 브랜드를 `scopedBrandById`로 검증 → 남의 org 질문 수정 차단.
 *   - `isAutoGenerated: false`(시스템 기본질문)는 수정 금지 — 폴백 측정의 원장이라
 *     고객이 바꾸면 측정이 깨진다(`delete-prompt.ts`와 같은 축 판단).
 *
 * ⚠️ `brandId_text`가 unique라 같은 브랜드에 이미 있는 텍스트로 바꾸면 DB 충돌이
 *   난다 — 저장 전에 직접 확인해 명확한 에러로 돌려준다(P2002를 그대로 흘리지 않는다).
 */

export type EditPromptResult = { ok: true } | { error: string };

export const editPromptAction = async (input: {
  promptId: string;
  text: string;
}): Promise<EditPromptResult> => {
  try {
    await requireOrg();
  } catch {
    return { error: "로그인 후 조직을 선택해 주세요." };
  }

  const text = input.text.trim();
  if (text.length < 3 || text.length > 200) {
    return { error: "질문은 3자 이상 200자 이하로 적어 주세요." };
  }

  const prompt = await database.prompt.findUnique({
    where: { id: input.promptId },
    select: { id: true, brandId: true, isAutoGenerated: true, text: true },
  });
  if (!prompt) {
    return { error: "질문을 찾을 수 없어요." };
  }

  // 🔒 이 질문의 브랜드가 현재 org 소속인지 검증(남의 org 차단).
  const brand = await scopedBrandById(prompt.brandId);
  if (!brand) {
    return { error: "질문을 찾을 수 없어요." };
  }

  // 🔴 시스템 기본질문은 고객이 고칠 수 없다(폴백 측정의 원장).
  if (!prompt.isAutoGenerated) {
    return {
      error: "기본 질문은 고칠 수 없어요. 직접 추가한 질문만 수정할 수 있어요.",
    };
  }

  if (text === prompt.text) {
    return { ok: true };
  }

  const duplicate = await database.prompt.findUnique({
    where: { brandId_text: { brandId: brand.id, text } },
    select: { id: true },
  });
  if (duplicate) {
    return { error: "이미 같은 내용의 질문이 있어요." };
  }

  try {
    await database.prompt.update({
      where: { id: prompt.id },
      data: { text },
    });
    log.info("brand.prompt.edited", { brandId: brand.id, promptId: prompt.id });
    return { ok: true };
  } catch (error) {
    log.error("brand.prompt.edit_failed", {
      brandId: brand.id,
      promptId: prompt.id,
      error: parseError(error),
    });
    return { error: "수정하지 못했어요. 잠시 후 다시 시도해 주세요." };
  }
};
