"use server";

import { resolveBrandIdentity } from "@repo/ai/lib/brand-identity";
import {
  normalizeTopic,
  type PromptSuggestions,
  type SuggestedPrompt,
  suggestTrackingPrompts,
} from "@repo/ai/lib/prompt-suggestions";
import { planCapabilities } from "@repo/auth/plan";
import { getCurrentPlan } from "@repo/auth/plan-server";
import { database } from "@repo/database";
import { parseError } from "@repo/observability/error";
import { log } from "@repo/observability/log";
import { requireOrg, scopedBrandById } from "@/lib/db/scoped";

/**
 * 프롬프트 자동 제안 마법사 서버 액션 (표준 백로그 1, 2026-07-30).
 *
 * 두 동작:
 *   1) suggestPromptsAction — AI가 추적 질문·경쟁사 후보를 생성(추가 LLM 호출 1). 저장 안 함.
 *   2) saveApprovedPromptsAction — 사용자가 승인한 프롬프트만 Prompt 테이블에 upsert(org 스코프).
 *
 * 🔒 보안(start-tracking.ts와 동일 불변식):
 *   - orgId: 세션에서 requireOrg()로 서버 재도출.
 *   - brandId: scopedBrandById로 "현재 org 소속"인지 검증 후에만 write(남의 org 브랜드 차단).
 *   - 저장 프롬프트는 감사 대상 텍스트만 받는다.
 *
 * 측정 반영: 저장된 프롬프트는 러너가 우선 사용(runner.ts). 없으면 기존 고정 4개 폴백 —
 *   원가·429 회귀 위험 없이 "승인분만 저장" 최소 연결(전략 결정 2026-07-30).
 */

export type SuggestPromptsResult =
  | { ok: true; suggestions: PromptSuggestions }
  | { error: string };

export const suggestPromptsAction = async (input: {
  brandId: string;
}): Promise<SuggestPromptsResult> => {
  try {
    await requireOrg();
  } catch {
    return { error: "로그인 후 조직을 선택해 주세요." };
  }

  const brand = await scopedBrandById(input.brandId);
  if (!brand) {
    return { error: "브랜드를 찾을 수 없습니다." };
  }

  try {
    // 대표 브랜드명 해석(한글 우선) 후 맥락 제안. resolveBrandIdentity는 사전·LLM 폴백 내장.
    const identity = await resolveBrandIdentity(brand.domain, brand.name);
    const suggestions = await suggestTrackingPrompts(
      identity.brandName,
      brand.domain,
      "both"
    );
    return { ok: true, suggestions };
  } catch (error) {
    log.error("brand.suggest_prompts.failed", {
      brandId: input.brandId,
      error: parseError(error),
    });
    return {
      error: "제안 생성 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    };
  }
};

export type SaveApprovedResult =
  // capped: 플랜 상한 때문에 선택분 중 일부만 저장됐을 때 true(업그레이드 안내용).
  //   requested = 사용자가 실제 저장 시도한(정제 후) 개수, limit = 현재 플랜 상한.
  | {
      ok: true;
      saved: number;
      capped?: boolean;
      requested?: number;
      limit?: number;
    }
  | { error: string };

// 🔴 N-42: `CATEGORY_MAP`(brand→recommendation · competitor→comparison)을 **없앴다**.
//   모든 질문이 이 표를 거치며 `recommendation`·`comparison` **2종으로 뭉개져서**
//   enum 7종 중 5종은 저장 경로가 아예 없었다(`best_in_category` 같은 GEO 핵심 유형이
//   한 번도 안 잡혔다). 이제 질문마다 LLM 이 판단한 `topic` 을 `normalizeTopic` 으로
//   좁혀 저장한다 — 폴백 기본값은 그 함수 안에 한 벌만 둔다(표를 두 곳에 두지 않는다).

export const saveApprovedPromptsAction = async (input: {
  brandId: string;
  prompts: SuggestedPrompt[];
}): Promise<SaveApprovedResult> => {
  try {
    await requireOrg();
  } catch {
    return { error: "로그인 후 조직을 선택해 주세요." };
  }

  const brand = await scopedBrandById(input.brandId);
  if (!brand) {
    return { error: "브랜드를 찾을 수 없습니다." };
  }

  // 저장 상한 = 플랜 능력치(게이팅 단일 진실). free 5·starter 30·growth 150…
  //   업계 화폐가 "추적 프롬프트 수"라 여기서 강제한다. 서버 판정(우회 불가).
  const plan = await getCurrentPlan();
  const promptLimit = planCapabilities(plan).promptLimit;

  // 입력 정제: 텍스트·언어 유효성 + 중복 제거.
  const seen = new Set<string>();
  const clean = input.prompts
    .map((p) => ({
      text: p.text.trim(),
      language: p.language,
      category: p.category,
      // 🔴 이 줄이 없으면 유형이 여기서 조용히 증발한다(N-42 이전 동작).
      topic: p.topic,
    }))
    .filter((p) => {
      const key = p.text.toLowerCase();
      const valid =
        p.text.length >= 3 &&
        p.text.length <= 200 &&
        (p.language === "ko" || p.language === "en") &&
        !seen.has(key);
      if (valid) {
        seen.add(key);
      }
      return valid;
    });

  if (clean.length === 0) {
    return { error: "저장할 프롬프트를 하나 이상 선택해 주세요." };
  }

  // 이미 저장된 auto 프롬프트 + 이번 저장분이 플랜 상한을 넘으면 차단(누적 기준).
  //   "몇 개 더 담을 수 있는지"를 안내해 업그레이드 경로로 유도.
  const existingCount = await database.prompt.count({
    where: { brandId: brand.id, isAutoGenerated: true },
  });
  const remaining = Math.max(0, promptLimit - existingCount);
  if (remaining === 0) {
    return {
      error: `현재 플랜의 추적 프롬프트 상한(${promptLimit}개)에 도달했어요. 더 많은 프롬프트를 추적하려면 요금제를 올려주세요.`,
    };
  }
  const capped = clean.slice(0, remaining);

  try {
    // tracking.ts와 동일한 brandId_text upsert — 재실행 시 promptId 안정(시계열 선 분열 방지).
    await database.$transaction(async (tx) => {
      for (const p of capped) {
        await tx.prompt.upsert({
          where: { brandId_text: { brandId: brand.id, text: p.text } },
          create: {
            brandId: brand.id,
            text: p.text,
            language: p.language,
            // LLM 이 판단한 유형을 쓴다. `normalizeTopic` 은 **항상 유효 enum 을 돌려준다**
            //   — 모르는 값·빈 값이면 균형축 기준 기본값(`CATEGORY_MAP` 과 같은 값)으로
            //   떨어진다. 신뢰 경계가 서버이므로 클라이언트 값을 그대로 믿지 않고 여기서 좁힌다.
            category: normalizeTopic(p.topic, p.category),
            isAutoGenerated: true,
          },
          update: {}, // 이미 있으면 텍스트·언어 불변.
          select: { id: true },
        });
      }
    });

    log.info("brand.prompts.saved", {
      brandId: brand.id,
      count: capped.length,
    });
    // 상한에 걸려 일부만 저장된 경우 신호(UI가 업그레이드 안내). 전부 저장이면 생략.
    const wasCapped = capped.length < clean.length;
    return {
      ok: true,
      saved: capped.length,
      ...(wasCapped
        ? { capped: true, requested: clean.length, limit: promptLimit }
        : {}),
    };
  } catch (error) {
    log.error("brand.save_prompts.failed", {
      brandId: input.brandId,
      error: parseError(error),
    });
    return { error: "프롬프트 저장 중 문제가 발생했습니다." };
  }
};
